const DATA = {
  nameStarts: [
   "Lumi", "Nova", "Mira", "Sera", "Fae", "Astra", "Cinna", "Mochi",
"Vel", "Nyla", "Rosie", "Coco", "Elli", "Pippa", "Junie", "Kira",
"Luna", "Nori", "Emi", "Rumi", "Mimi", "Lila", "Zuri", "Opal",
"Fina", "Ari", "Rina", "Melo", "Yumi", "Taffy", "Bunni", "Lottie",
"Skye", "Tori", "Maple", "Sunny", "Peony", "Winnie", "Lacey", "Mika",
"Nixi", "Bree", "Dottie", "Rika", "Pixi", "Honey", "Daisy", "Maru",
"Suki", "Koko", "Finae", "Auri", "Kiki", "Mello", "Riri", "Starry",
"Airi", "Luma","Vivi", "Momo", "Nini", "Poki", "Chai", "Lyra", "Runa", "Noa",
"Eira", "Miri", "Fifi", "Tina", "Kona", "Sora", "Yuki", "Aika",
"Remi", "Rory", "Tali", "Miri", "Nene", "Lulu", "Sukiya", "Mirae",
"Anya", "Ririi", "Puri", "Mikae", "Sena", "Vela", "Liora", "Niva",
"Ayla", "Ceri", "Eirae", "Nixie", "Mikai", "Fiora", "Ciel", "Rhea",
"Ami", "Nia", "Penny", "Tika", "Vani", "Mallow", "Dewi", "Sola",
"Aurii", "Clover"
  ],

  nameEnds: [
    "belle", "luna", "rose", "star", "mimi", "bean", "wyn", "elle",
    "berry", "whisk", "bloom", "sprout", "mara", "shine", "puff", "moon", "elle", "ella", "ina", "inae", "ira", "irae", "ara", "arae",
"ora", "oria", "orae", "una", "unae", "ika", "ikae", "ikaa",
"ikai", "ikae", "ikaa", "ikaia", "ikaine", "ikaelle", "ikaira", "ikaora",
"ette", "etta", "etti", "ettia", "lyn", "lynn", "line", "lina",
"lene", "lena", "lise", "lisa", "ria", "rielle", "riel", "riellea",
"rina", "rinae", "rinae", "rinaelle", "rinaira", "rinaora", "risa", "rissa",
"mie", "mia", "mina", "mira", "mirae", "mielle", "mila", "milia",
"nelle", "nellea", "nette", "netta", "nina", "nia", "nielle", "niellea",
"yuki", "yuna", "yume", "yori", "yora", "yelle", "yette", "yina",
"ettea", "ellie", "ellia", "eena", "eira", "eirae", "eila", "eille",
"belle", "bella", "blossom", "berry", "bun", "bean", "boo", "pop",
"puff", "petal", "peach", "pie", "sprout", "song", "shine", "star",
"moon", "dream", "whisp", "mist", "dew", "dove", "kiss", "heart",
"tail", "wing", "leaf", "bloom", "drop", "cloud"
  ],

  surnames: [
    "Moonwhisk", "Starfall", "Velvetbrew", "Sweetspark", "Duskgarden",
    "Cloudberry", "Nightbloom", "Sugarveil", "Lavenderlace", "Coffeebean", "Starfall", "Moonwhisper", "Dewdrop", "Cloudberry", "Honeybell", "Rosebloom", "Willowmere", "Lavender",
"Starlight", "Moonvale", "Petalbrook", "Sunpetal", "Dreamleaf", "Snowbell", "Mapledew", "Rosethorn",
"Silvermist", "Skydancer", "Meadowlark", "Softwind", "Starweaver", "Moonweaver", "Rainblossom", "Sweetbriar",
"Fernbrook", "Cherryvale", "Berrybloom", "Moonflower", "Starling", "Hazelgrove", "Ivydream", "Pinewhisper",
"Cloudsong", "Lilacbreeze", "Honeyfield", "Rosewater", "Mistvale", "Dreamsong", "Sunwillow", "Peachgrove",
"Frostpetal", "Daisybrook", "Cloverfield", "Meadowshade", "Starbloom", "Mooncrest", "Willowshade", "Bloomheart",
"Softpetal", "Silverbrook", "Mosswhisper", "Foxglove", "Riversong", "Moonbrook", "Dewwhisper", "Starglade",
"Rainwhisper", "Hazelmist", "Skymallow", "Velvetrose", "Suncrest", "Mooncrest", "Starcrest", "Morningshade",
"Everdew", "Petalsong", "Wildbloom", "Willowbloom", "Meadowmist", "Cloudwhisper", "Honeydew", "Snowbloom",
"Maplewhisper", "Roselight", "Berrysong", "Lilybrook", "Starbrook", "Moonbrook", "Softbrook", "Rainbrook",
"Peachblossom", "Honeyblossom", "Lilacgrove", "Sagefield", "Morningdew", "Dreamwillow", "Silverleaf", "Fernsong",
"Roseveil", "Moonveil", "Starveil", "Skylark", "Fawnheart", "Amberfield", "Cinnamonvale", "Sugarbloom",
"Moonhaven", "Starhaven", "Cloudhaven", "Willowhaven", "Rosehaven", "Meadowhaven", "Berryhaven", "Honeyhaven",
"Sunhaven", "Dreamhaven", "Mistbloom", "Moonpetal", "Starpetal", "Rosedream", "Skydream", "Fernvale",
"Maplevale", "Lilacvale", "Cloudvale", "Peachvale", "Honeyvale", "Snowvale", "Rosegrove", "Moonshade",
"Starshade", "Berryshade", "Petalshade", "Willowgrove", "Silvergrove", "Dawnwhisper", "Twilightbloom", "Dreammist",
"Moonmist", "Starmist", "Rosemist", "Peachmist", "Cloudmist", "Silvermist", "Honeymist", "Berrymist",
"Sunmist", "Dewmist", "Mallowbrook", "Sugarbrook", "Velvetbrook", "Lacefield", "Ivoryvale", "Snowberry",
"Moonberry", "Starberry", "Honeyberry", "Peachberry", "Roseberry", "Cloverberry", "Dreamberry", "Cloudberry",
"Moonsong", "Starsong", "Rosesong", "Willowsong", "Dreamsong", "Silversong", "Skysong", "Berrysong",
"Petalheart", "Moonheart", "Starheart", "Roseheart", "Honeyheart", "Dreamheart", "Silverheart", "Sunheart",
"Cloudheart", "Willowheart", "Fawnsong", "Meadowheart", "Snowheart", "Bloomsong", "Softsong", "Lavenderfield",
"Goldenleaf", "Autumnbloom", "Summerdew", "Springwhisper", "Winterrose", "Crescentvale", "Celestine", "Moonridge",
"Starridge", "Rosemeadow", "Honeymeadow", "Cloudmeadow", "Dreammeadow", "Petalmeadow", "Willowmeadow", "Silverbell",
"Moonbell", "Starbell", "Rosebell", "Berrybell", "Honeybell", "Snowbell", "Dreambell", "Cloudbell"
  ],

  species: [
   "Bunny", "Bat", "Bear", "Red Panda", "Coffee Fox", "Cloud Cat",
"Unicorn", "Panda", "Canine", "Cow", "Dragon Bunny", "Alien Bun",
"Deer", "Capybara", "Raccoon", "Cat", "Dog", "Wolf", "Fox",
"Fennec Fox", "Arctic Fox", "Otter", "Ferret", "Pine Marten", "Weasel",
"Mouse", "Rat", "Hamster", "Guinea Pig", "Chinchilla", "Hedgehog",
"Skunk", "Possum", "Squirrel", "Chipmunk", "Beaver", "Badger",
"Raccoon Dog", "Tanuki", "Coyote", "Jackal", "Hyena", "Lion",
"Tiger", "Leopard", "Panther", "Snow Leopard", "Lynx", "Bobcat",
"Cheetah", "Cougar", "Jaguar", "Serval", "Caracal", "Pallas Cat",
"Goat", "Sheep", "Alpaca", "Llama", "Horse", "Pony",
"Donkey", "Pig", "Boar", "Moose", "Elk", "Reindeer",
"Gazelle", "Antelope", "Buffalo", "Bison", "Yak", "Camel",
"Giraffe", "Elephant", "Hippo", "Tapir", "Sloth", "Koala",
"Kangaroo", "Wallaby", "Quokka", "Platypus", "Wombat", "Armadillo",
"Seal", "Sea Lion", "Dolphin", "Whale", "Shark", "Axolotl",
"Frog", "Salamander", "Gecko", "Chameleon", "Snake", "Turtle",
"Alligator", "Crocodile", "Dragon", "Eastern Dragon", "Sea Dragon", "Fairy Dragon",
"Kirin", "Qilin", "Pegasus", "Griffin", "Jackalope", "Kitsune",
"Wolpertinger", "Moth Cat", "Star Bunny", "Moon Bat", "Sun Lion",
"Cloud Sheep", "Dream Deer", "Galaxy Wolf", "Cosmic Fox", "Candy Bear",
"Strawberry Cow", "Mochi Bunny", "Boba Cat", "Cookie Panda", "Marshmallow Fox",
"Pastel Deer", "Crystal Unicorn", "Moon Rabbit", "Tea Raccoon", "Lantern Goat",
"Plush Dragon", "Candle Cat", "Jelly Bunny", "Velvet Bat", "Star Panda",
"Fawn Dog", "Honey Bear", "Sakura Fox", "Celestial Deer", "Nebula Cat",
"Coffee Cat", "Matcha Bunny", "Taiyaki Fox", "Dango Deer", "Cake Bat",
"Galaxy Bunny", "Space Otter", "Alien Cat", "Void Fox", "Dream Panda",
"Cloud Bunny", "Sunflower Deer", "Rose Goat", "Mushroom Raccoon", "Pumpkin Bear",
"Moon Fox", "Star Sheep", "Aurora Wolf", "Comet Cat", "Spirit Deer"
  ],

  themes: [
    "Strawberry Cafe", "Moonlit Bakery", "Celestial Gothic", "Pastel Arcade",
"Cozy Rainy-Day Bookstore", "Magic Flower Stall", "Candy Witch",
"Dreamy Sleepover", "Starry Coffeehouse", "Autumn Harvest Market",
"Kawaii Seamstress", "Gothic Tea Party", "Cherry Blossom Festival",
"Moonflower Garden", "Cloudy Tea House", "Cozy Library", "Sunset Beach Cafe",
"Plushie Collector", "Sweet Lolita", "Galaxy Aquarium", "Fairy Tailor",
"Vintage Bakery", "Moon Rabbit Shrine", "Star Festival", "Bubble Tea Shop",
"Cottagecore Farm", "Pumpkin Patch", "Rainy Train Station", "Magical Florist",
"Crystal Cavern", "Dreamy Pajama Party", "Forest Apothecary", "Witch's Kitchen",
"Pastel Carnival", "Moonlight Picnic", "Cozy Cat Cafe", "Candy Shop",
"Enchanted Toy Store", "Ice Cream Parlor", "Cookie Bakery", "Sunflower Meadow",
"Celestial Observatory", "Star Gazing Club", "Night Market", "Lantern Festival",
"Book Nook Cafe", "Sleepy Village", "Rainy Day Diner", "Moonlit Alley",
"Magical Aquarium", "Vintage Arcade", "Gothic Boutique", "Mushroom Cottage",
"Tea Garden", "Cloud Kingdom", "Dreamcore Bedroom", "Moonlit Forest",
"Cherry Tea Shop", "Starry Bedroom", "Coastal Boardwalk", "Seaside Bakery",
"Fantasy Inn", "Wizard Library", "Potion Shop", "Crystal Garden",
"Moon Cafe", "Cloud Bakery", "Candy Kingdom", "Sakura Festival",
"Forest Cabin", "Lavender Fields", "Cozy Fireplace", "Sunrise Meadow",
"Moonlight Ballroom", "Royal Tea Room", "Fairy Market", "Kawaii Idol",
"Pastel Princess", "Gothic Princess", "Moon Shrine", "Starlight Theater",
"Dream Journal", "Plush Workshop", "Handmade Crafts", "Knitting Club",
"Tea Time Picnic", "Cookie Decorating", "Rainy Window Seat", "Moonlit Rooftop",
"Star Bakery", "Celestial Library", "Rose Garden", "Lily Pond",
"Flower Crown Shop", "Vintage Tailor", "Crystal Boutique", "Sweet Café Date",
"Nighttime Carnival", "Cozy Campsite", "Winter Market", "Spring Festival",
"Summer Fireflies", "Autumn Leaves", "Snowy Village", "Rainy City Lights",
"Moon Jellyfish Aquarium", "Galaxy Planetarium", "Dreamy Bedroom", "Pastel Kitchen",
"Sunrise Cafe", "Moonrise Diner", "Bunny Bakery", "Fox Tea House",
"Bear Honey Shop", "Deer Flower Farm", "Cloud Observatory", "Star Fountain",
"Moon Garden", "Sunflower Cafe", "Rainy Bus Stop", "Vintage Record Store",
"Cozy Reading Corner", "Art Studio", "Paint Night", "Scrapbook Club",
"Pottery Studio", "Embroidery Circle", "Crochet Club", "Candle Shop",
"Perfume Boutique", "Jewelry Store", "Antique Market", "Magic School",
"Witch Academy", "Fairy Classroom", "Dragon Library", "Moon Cathedral",
"Gothic Cathedral", "Rose Manor", "Victorian Tea Room", "Haunted Mansion",
"Ghost Cafe", "Moonlit Cemetery", "Pumpkin Bakery", "Candy Manor",
"Celestial Palace", "Dream Palace", "Royal Garden", "Cherry Orchard",
"Blueberry Farm", "Strawberry Festival", "Peach Orchard", "Honey Farm",
"Bee Keeper Cottage", "Moonflower Conservatory", "Cloud Palace", "Star Observatory",
"Fairy Ring", "Mushroom Village", "Moon Bunny Burrow", "Plush Kingdom",
"Cozy Blanket Fort", "Dream Sleepover", "Movie Marathon Night", "Board Game Cafe",
"Video Game Arcade", "Retro Arcade", "Magical Arcade", "Kawaii Maid Cafe",
"Gothic Maid Cafe", "Boba Tea Shop", "Milkshake Bar", "Pastry Shop",
"Chocolate Factory", "Candy Factory", "Moonlight Harbor", "Rainy Harbor Town",
"Fishing Village", "Beach Festival", "Ocean Aquarium", "Coral Garden",
"Crystal Beach", "Mermaid Lagoon", "Starry Planetarium", "Galaxy Museum",
"Moon Museum", "Art Gallery", "Photo Studio", "Music Room",
"Piano Lounge", "Jazz Cafe", "Moonlight Concert", "Star Idol Stage",
"Flower Festival", "Lantern Parade", "Cherry Moon Festival", "Cosmic Carnival",
"Tea Witch Cottage", "Moon Mage Tower", "Sun Mage Tower", "Celestial Chapel",
"Dream Bakery", "Star Weaver Studio", "Magic Quilt Shop", "Pastel Toy Shop",
"Rainy Flower Shop", "Moonlit Greenhouse", "Cloud Nursery", "Sunset Rooftop Garden",
"Cat Nap Cafe", "Foxfire Tavern", "Cozy Attic Bedroom", "Star Nursery",
"Fairy Bakery", "Lavender Tea House", "Moonflower Bookstore", "Celestial Sewing Room"
  ],

  palettes: [
   "Dusty pink, cream, espresso brown",
"Lavender, black, silver",
"Baby blue, cloud white, soft gold",
"Chocolate brown, rose pink, vanilla",
"Mint, peach, warm cream",
"Deep purple, magenta, moonlight silver",
"Pastel rainbow, white, candy pink",
"Forest green, honey yellow, warm brown",
"Sky blue, lavender, pearl white",
"Sage green, cream, dusty rose",
"Strawberry pink, milk white, cocoa brown",
"Moonlight blue, silver, midnight navy",
"Peach, coral, warm ivory",
"Mint green, white, pale yellow",
"Soft lilac, blush pink, cream",
"Black, crimson, silver",
"Plum purple, charcoal, lavender",
"Rose gold, ivory, champagne",
"Sunflower yellow, sage green, cream",
"Ocean blue, seafoam, sandy beige",
"Teal, peach, white",
"Sky blue, lemon yellow, white",
"Ruby red, black, gold",
"Emerald green, cream, copper",
"Periwinkle, pink, white",
"Coffee brown, caramel, cream",
"Soft orange, honey, vanilla",
"Lavender, mint, baby pink",
"Cotton candy pink, aqua, white",
"Storm gray, silver, icy blue",
"Wine red, blush pink, black",
"Pastel yellow, mint, lavender",
"Powder blue, silver, white",
"Coral pink, cream, mocha",
"Midnight blue, violet, silver",
"Sakura pink, white, pale green",
"Chocolate, cream, strawberry pink",
"Berry purple, blush, cream",
"Rose red, black, ivory",
"Honey gold, cream, cinnamon",
"Seafoam green, sky blue, white",
"Lilac, silver, moon white",
"Baby pink, lavender, mint",
"Peach cream, cocoa, rose pink",
"Sunset orange, coral, cream",
"Indigo, silver, pale lavender",
"Forest green, cream, amber",
"Blueberry blue, cream, lilac",
"Warm beige, caramel, espresso",
"Cloud gray, baby blue, white",
"Rose pink, mauve, cream",
"Mint green, cocoa brown, vanilla",
"Silver, navy, moon blue",
"Soft red, cream, dusty pink",
"Pumpkin orange, sage green, cream",
"Black, purple, rose gold",
"Golden yellow, white, honey brown",
"Sky blue, mint, cream",
"Bubblegum pink, white, pale blue",
"Maroon, black, gold",
"Teal, navy, silver",
"Strawberry pink, cream, mint",
"Mocha brown, dusty rose, ivory",
"Peach, lavender, white",
"Pastel blue, lemon, pink",
"Dark green, copper, beige",
"Coral, aqua, white",
"Periwinkle, cream, pale gold",
"Rose pink, pearl white, silver",
"Chocolate brown, vanilla, caramel",
"Black, crimson, moon silver",
"Sage green, peach, cream",
"Blue gray, silver, white",
"Deep teal, pale gold, ivory",
"Plum purple, pink, cream",
"Cherry red, black, white",
"Cloud white, baby pink, lavender",
"Honey yellow, cream, soft orange",
"Emerald green, gold, black",
"Peach pink, warm white, cocoa",
"Sky blue, moon silver, navy",
"Mint green, white, pastel pink",
"Lilac purple, cream, silver",
"Rosewood, blush pink, ivory",
"Caramel, cream, honey gold",
"Blueberry, lavender, cream",
"Black, silver, wine red",
"Sea blue, white, coral",
"Pastel mint, peach, white",
"Strawberry red, cream, chocolate",
"Moon blue, lavender, silver",
"Sage green, ivory, mocha",
"Cloud white, pale yellow, blue",
"Magenta, deep purple, silver",
"Rose gold, blush, cream",
"Sky blue, lilac, white",
"Espresso brown, cream, soft pink",
"Sunflower yellow, peach, cream",
"Periwinkle, pink, mint",
"Charcoal gray, lavender, silver",
"Coral pink, white, gold",
"Baby blue, silver, lavender",
"Cinnamon brown, cream, blush",
"Forest green, beige, amber",
"Mint, ivory, pale gold",
"Chocolate brown, cherry red, cream",
"Rose pink, white, soft gray",
"Moonlight silver, navy, pale blue",
"Strawberry milk pink, cream, cocoa",
"Lemon yellow, white, mint",
"Royal purple, black, silver",
"Soft aqua, white, pearl",
"Honey gold, mocha, cream",
"Blush pink, sage green, ivory",
"Blue lavender, white, silver",
"Rose red, cream, champagne",
"Midnight navy, silver, lavender",
"Peach, strawberry pink, vanilla",
"Soft green, cream, honey",
"Baby pink, white, pale yellow",
"Berry purple, moon silver, black",
"Cloud blue, cream, lavender",
"Mint, blush pink, white",
"Copper, cream, espresso",
"Coral orange, pale yellow, white",
"Periwinkle blue, pearl, pink",
"Rosewood red, gold, cream",
"Sky blue, cloud gray, white",
"Chocolate brown, vanilla cream, pink",
"Lavender, moon blue, silver",
"Forest moss, honey, cream",
"Candy pink, pastel blue, white",
"Teal green, cream, peach",
"Midnight purple, silver, black",
"Peach cream, dusty rose, ivory",
"Baby blue, mint, white",
"Warm caramel, cream, coffee brown",
"Rose quartz pink, silver, white",
"Seafoam green, ivory, pale blue",
"Crimson, black, silver",
"Plum, blush pink, cream",
"Honey yellow, sage, beige",
"Pastel rainbow, pearl white, lavender",
"Soft coral, vanilla, cocoa",
"Moonlight blue, cloud white, silver",
"Espresso brown, cream, caramel",
"Sakura pink, pearl, mint",
"Storm gray, navy, silver",
"Mint green, pale peach, ivory",
"Rose pink, chocolate brown, cream",
"Sunset peach, lavender, white",
"Berry blue, silver, white",
"Warm cream, honey gold, brown",
"Black, plum, rose gold",
"Sky blue, pale lavender, pearl",
"Forest green, cream, cinnamon",
"Blueberry purple, pink, white",
"Vanilla cream, blush, caramel",
"Deep navy, moon silver, white",
"Peach pink, mint green, cream",
"Cherry blossom pink, white, gold",
"Teal blue, silver, ivory",
"Soft yellow, cream, peach",
"Rose red, black, moon silver",
"Baby blue, cotton pink, white",
"Sage green, dusty rose, cream",
"Chocolate brown, strawberry pink, vanilla",
"Lavender gray, silver, white",
"Sunflower yellow, honey brown, cream",
"Mint blue, white, silver",
"Pastel peach, lilac, cream",
"Forest green, amber, ivory",
"Deep purple, pink, silver",
"Pearl white, blush pink, champagne",
"Caramel brown, cream, rose",
"Sky blue, moon white, pale gold",
"Seafoam, mint, ivory",
"Black, magenta, silver",
"Berry pink, cream, mocha",
"Cloud white, baby blue, lavender",
"Honey gold, cream, sage green",
"Rosewood, blush, moon silver",
"Bluebell blue, white, pink",
"Espresso brown, vanilla, honey",
"Peach, coral pink, ivory",
"Midnight blue, lavender, moon silver"
  ],

  personalities: [
    "soft-spoken", "dramatic", "bratty", "motherly", "mischievous",
"sleepy", "spoiled", "loyal", "chaotic", "gentle", "protective",
"curious", "flirty", "bookish", "clumsy", "confident",
"shy", "timid", "bashful", "playful", "cheerful", "optimistic",
"pessimistic", "sarcastic", "witty", "goofy", "energetic", "hyper",
"laid-back", "easygoing", "reserved", "quiet", "talkative", "bubbly",
"affectionate", "clingy", "attention-seeking", "stubborn", "determined",
"independent", "dependable", "caring", "nurturing", "patient",
"impatient", "romantic", "dreamy", "creative", "artistic", "musical",
"organized", "messy", "scatterbrained", "forgetful", "responsible",
"mature", "childish", "whimsical", "eccentric", "elegant", "graceful",
"awkward", "anxious", "worry-prone", "sensitive", "empathetic",
"compassionate", "kind-hearted", "selfless", "selfish", "vain",
"vain-but-sweet", "fashionable", "stylish", "trendy", "old-fashioned",
"traditional", "rebellious", "free-spirited", "adventurous",
"cautious", "carefree", "reckless", "bold", "fearless", "cowardly",
"competitive", "cooperative", "helpful", "supportive", "observant",
"analytical", "logical", "emotional", "passionate", "fiery",
"hot-headed", "calm", "collected", "stoic", "mysterious",
"secretive", "honest", "blunt", "polite", "well-mannered",
"sassy", "snarky", "teasing", "friendly", "welcoming",
"charismatic", "charming", "sweet", "innocent", "naive",
"street-smart", "clever", "resourceful", "hardworking", "lazy",
"sleep-loving", "foodie", "tea-loving", "coffee-obsessed",
"workaholic", "perfectionist", "ambitious", "content", "humble",
"prideful", "grumpy", "tsundere", "kuudere", "yandere",
"deredere", "airheaded", "ditzy", "gullible", "trusting",
"suspicious", "guarded", "protective-big-sibling", "mother-hen",
"big-hearted", "gentle giant", "tiny menace", "gremlin",
"chaos goblin", "prankster", "joker", "class clown",
"daydreamer", "starry-eyed", "hopeful", "sentimental", "nostalgic",
"melancholic", "brooding", "gothic", "spooky", "witchy",
"nature-loving", "animal-loving", "bookworm", "scholarly",
"intellectual", "nerdy", "tech-savvy", "crafty", "resourceful",
"perceptive", "intuitive", "wise", "motherly-but-strict",
"gentle-but-firm", "soft-hearted", "forgiving", "vengeful",
"jealous", "possessive", "devoted", "faithful", "protective-big-brother",
"protective-big-sister", "clingy-but-caring", "shameless",
"dramatic-princess", "spoiled-princess", "cozy", "homebody",
"social butterfly", "introverted", "extroverted", "ambiverted",
"adorkable", "excitable", "curiosity-driven", "peaceful",
"serene", "radiant", "sunny", "moonlike", "starry-eyed",
"softie", "cinnamon-roll", "crybaby", "resilient", "tenacious",
"headstrong", "gentle soul", "warm-hearted", "lovable menace",
"unapologetically herself", "surprisingly nurturing"
  ],

  occupations: [
 "barista", "florist", "librarian", "potion seller", "plushie maker",
"night bakery assistant", "fashion designer", "cafe owner",
"fortune teller", "arcade attendant", "jewelry apprentice",
"traveling snack vendor", "baker", "pastry chef", "tea shop owner",
"bookstore clerk", "toy maker", "candlemaker", "tailor",
"seamstress", "dressmaker", "embroidery artist", "crochet artist",
"knitting instructor", "ceramic artist", "potter", "painter",
"illustrator", "comic artist", "tattoo artist", "graphic designer",
"calligrapher", "scrapbook artist", "sticker designer", "plush repairer",
"doll maker", "toy collector", "stationery designer", "journal maker",
"perfumer", "soap maker", "flower arranger", "gardener",
"greenhouse keeper", "herbalist", "tea blender", "beekeeper",
"honey farmer", "fruit picker", "jam maker", "cheesemaker",
"chocolatier", "ice cream vendor", "candy maker", "ramen chef",
"sushi chef", "food truck owner", "street vendor", "picnic planner",
"wedding planner", "party decorator", "event coordinator",
"festival organizer", "maid cafe hostess", "cat cafe manager",
"animal shelter worker", "pet groomer", "dog trainer",
"veterinary assistant", "aquarium caretaker", "bird sanctuary keeper",
"horse trainer", "stable hand", "rancher", "farmer",
"shepherd", "fisher", "boat captain", "lighthouse keeper",
"park ranger", "forest guide", "camp counselor", "tour guide",
"museum curator", "art gallery owner", "historian", "archivist",
"researcher", "teacher", "tutor", "professor",
"kindergarten teacher", "music teacher", "dance instructor",
"piano instructor", "choir director", "violinist", "cellist",
"singer", "idol", "voice actor", "radio host",
"podcaster", "news reporter", "photographer", "videographer",
"filmmaker", "streamer", "game developer", "programmer",
"web designer", "app developer", "robotics engineer", "inventor",
"clockmaker", "watchmaker", "jeweler", "gem cutter",
"blacksmith", "silversmith", "woodworker", "carpenter",
"furniture maker", "architect", "interior designer", "landscape designer",
"real estate agent", "hotel receptionist", "innkeeper",
"bed and breakfast owner", "housekeeper", "butler", "maid",
"babysitter", "nanny", "caregiver", "nurse",
"doctor", "dentist", "pharmacist", "therapist",
"counselor", "life coach", "yoga instructor", "fitness trainer",
"masseuse", "spa attendant", "makeup artist", "hair stylist",
"nail artist", "esthetician", "fashion model", "costume designer",
"cosplayer", "stage actor", "circus performer", "magician",
"puppeteer", "storyteller", "author", "poet",
"novelist", "translator", "editor", "bookbinder",
"mail carrier", "courier", "train conductor", "bus driver",
"taxi driver", "delivery driver", "mechanic", "electrician",
"plumber", "firefighter", "police officer", "security guard",
"astronomer", "planetarium guide", "weather reporter",
"cloud researcher", "dream analyst", "star chart maker",
"fortune cookie writer", "tarot reader", "crystal shop owner",
"witch", "moon priestess", "temple caretaker", "shrine maiden",
"dragon caretaker", "fairy researcher", "spellbook librarian",
"magic teacher", "wand maker", "rune engraver",
"potion brewer", "alchemist", "enchanter", "magic tailor",
"monster veterinarian", "griffin stable keeper", "cloud shepherd",
"lantern maker", "starweaver", "dream catcher artisan",
"moonflower gardener", "festival lantern seller", "tea witch",
"candy witch", "traveling bard", "treasure hunter",
"antique dealer", "pawn shop owner", "clock tower keeper",
"observatory assistant", "cat sitter", "plush collector",
"board game cafe host", "arcade owner", "bubble tea maker",
"cozy inn owner", "flower cart vendor", "pastry decorator",
"cake artist", "moonlight market vendor", "jelly maker",
"fortune cookie baker", "seashell collector", "postcard illustrator"
  ],

  aesthetics: [
    "pastel goth", "cozy cottagecore", "celestial kawaii", "soft gothic",
"candycore", "dreamy cafe", "moon witch", "storybook cute",
"rainy-day cozy", "starry streetwear", "sweet lolita", "sleepy plushcore",
"fairycore", "angelcore", "dreamcore", "kidcore",
"softcore", "cloudcore", "mooncore", "starcore",
"spacecore", "galaxycore", "sunsetcore", "sunrisecore",
"berrycore", "strawberrycore", "peachcore", "lavendercore",
"honeycore", "teacore", "coffeecore", "bakerycore",
"bunnycore", "catcore", "foxcore", "bearcore",
"deercore", "pandacore", "batcore", "dragoncore",
"forestcore", "mushroomcore", "flowercore", "gardencore",
"rosecore", "lilycore", "sunflowercore", "ivycore",
"sakuracore", "meadowcore", "raincore", "stormcore",
"mistcore", "snowcore", "wintercore", "autumncore",
"springcore", "summercore", "nightcore", "twilightcore",
"midnightcore", "moonlit cottagecore", "vintage bakery", "tea party chic",
"victorian gothic", "gothic lolita", "classic lolita", "princesscore",
"royalcore", "fairytalecore", "storybook whimsy", "storybook fantasy",
"plushcore", "toycore", "sanriocore", "kawaiicore",
"bubblegum pop", "cotton candycore", "jellycore", "dessertcore",
"cookiecore", "chocolatecore", "marshmallowcore", "ice creamcore",
"boba tea aesthetic", "maid cafe", "arcade pastel", "retro kawaii",
"retro arcade", "y2k pastel", "yume kawaii", "decora kei",
"harajuku cute", "pastel streetwear", "goth streetwear", "star idol",
"idolcore", "magical girl", "witchcore", "tea witch",
"candy witch", "moon priestess", "celestial witch", "crystal witch",
"tarotcore", "potioncore", "alchemycore", "fantasy academia",
"light academia", "dark academia", "bookworm chic", "librarycore",
"rainy bookstore", "cozy library", "journalcore", "stationerycore",
"scrapbookcore", "craftcore", "crochetcore", "knittingcore",
"embroiderycore", "sewingcore", "artsy pastel", "paintcore",
"musiccore", "pianocore", "vinylcore", "jazz lounge",
"coffeehouse chic", "cat cafe", "bunny cafe", "flower shop aesthetic",
"greenhousecore", "apothecarycore", "candlecore", "perfumecore",
"spa aesthetic", "cozy pajamas", "sleepovercore", "blanket fort",
"pillow princess", "cozy gamer", "streamercore", "deskcore",
"plant mom aesthetic", "homebody chic", "minimal kawaii", "soft minimalism",
"vintage pastel", "retro diner", "retro sweetheart", "polaroidcore",
"lacecore", "ribboncore", "pearlcore", "rose gold aesthetic",
"moonlight elegance", "silver celestial", "velvet gothic", "black lace",
"romantic gothic", "vampire chic", "gothic romance", "haunted elegance",
"ghostcore", "spooky cute", "pumpkincore", "halloween kawaii",
"coffin cute", "batty pastel", "midnight garden", "enchanted forest",
"fairy garden", "cottage witch", "elfcore", "faecore",
"mermaidcore", "seacore", "aquariumcore", "shellcore",
"coral pastel", "beach cottage", "boardwalk retro", "coastal grandma",
"coastal cute", "sunflower picnic", "picniccore", "campfire cozy",
"lantern festival", "night market", "festivalcore", "fireflycore",
"cloud kingdom", "dream palace", "celestial palace", "princess bedroom",
"nurserycore", "babycore", "teddybearcore", "plush collector",
"cozy attic", "atticcore", "moon bunny aesthetic", "star bunny aesthetic",
"nebula chic", "cosmic dreamcore", "constellationcore", "auroracore",
"crystalcore", "gemcore", "opalcore", "moonstone elegance",
"honey bee cottagecore", "lavender fields", "rainy window aesthetic",
"warm fireplace", "tea and books", "soft celestial", "moonflower chic",
"sleepy sunday", "cozy rainy cafe", "starlight elegance", "pastel celestial"
  ],

  accessories: [
  "crescent moon hair clips", "oversized hoodie", "tiny star purse",
"heart-shaped glasses", "ribbon collar", "plush backpack",
"coffee cup charm", "lace gloves", "strawberry earrings",
"spellbook satchel", "fluffy slippers", "moon pendant", "star pendant", "sun pendant", "heart locket",
"locket necklace", "charm bracelet", "friendship bracelet",
"pearl bracelet", "lace choker", "ribbon choker",
"bell collar", "bow tie collar", "gem collar",
"flower crown", "rose crown", "sunflower crown",
"moon tiara", "crystal tiara", "star headband",
"cat ear headband", "bunny ear headband", "bat wing headband",
"halo headpiece", "lace bonnet", "beret",
"knitted beanie", "pom-pom hat", "witch hat",
"sun hat", "straw hat", "newsboy cap",
"baseball cap", "hooded cape", "poncho",
"shawl", "lace shawl", "cardigan",
"cropped jacket", "oversized scarf", "fluffy scarf",
"plaid scarf", "leg warmers", "striped socks",
"knee-high socks", "lace stockings", "fishnet stockings",
"fingerless gloves", "mittens", "arm warmers",
"lace arm sleeves", "ribbon wrist cuffs", "bracelet stack",
"anklet", "toe ring", "promise ring",
"moonstone ring", "rose ring", "star ring",
"flower earrings", "moon earrings", "star earrings",
"heart earrings", "crystal earrings", "pearl earrings",
"mismatch earrings", "dangling earrings", "clip-on earrings",
"hair bows", "double hair bows", "ribbon scrunchie",
"star scrunchie", "flower hair pin", "butterfly clip",
"moon hair comb", "pearl hair chain", "braided ribbon",
"hair beads", "hair charms", "hair ribbon",
"hair flowers", "flower barrettes", "star barrettes",
"lace eyepatch", "round glasses", "gold-rim glasses",
"rose-tinted glasses", "moon sunglasses", "star sunglasses",
"tiny backpack", "mini purse", "crossbody bag",
"satchel", "messenger bag", "book bag",
"moon purse", "cloud purse", "bunny purse",
"bear purse", "cat purse", "bat purse",
"strawberry purse", "cake purse", "milk carton purse",
"potion bottle purse", "crescent moon purse", "plush purse",
"coin pouch", "wallet chain", "phone charm",
"star phone charm", "bunny phone charm", "strap keychain",
"plush keychain", "heart keychain", "flower keychain",
"tiny bell keychain", "lucky charm", "dreamcatcher charm",
"book charm", "tea cup charm", "moon charm",
"star charm", "sun charm", "cloud charm",
"rainbow charm", "berry charm", "cookie charm",
"cake charm", "ice cream charm", "boba charm",
"crochet tote", "canvas tote", "flower tote",
"moon tote", "star tote", "cat tote",
"bear tote", "bunny tote", "book tote",
"patchwork tote", "lace parasol", "frilly parasol",
"sun umbrella", "moon umbrella", "clear umbrella",
"flower umbrella", "star umbrella", "ribbon umbrella",
"tiny notebook", "journal", "sticker binder",
"scrapbook", "photo album", "bookmark tassel",
"bookmark charm", "mini sketchbook", "fountain pen",
"quill pen", "wax seal kit", "ink bottle necklace",
"pocket watch", "star pocket watch", "moon pocket watch",
"compact mirror", "heart mirror", "flower mirror",
"perfume atomizer", "lip balm holder", "makeup pouch",
"brush case", "travel case", "tea tin",
"cookie tin", "bento bag", "lunch tote",
"sleep mask", "moon sleep mask", "star sleep mask",
"plush neck pillow", "travel pillow", "blanket shawl",
"paw slippers", "bunny slippers", "bear slippers",
"moon slippers", "star slippers", "cloud slippers",
"rain boots", "lace-up boots", "platform shoes",
"mary janes", "ballet flats", "ribbon heels",
"moon heels", "star sneakers", "light-up sneakers",
"crystal brooch", "rose brooch", "bow brooch",
"star brooch", "moon brooch", "cameo brooch",
"lace apron", "frilly apron", "maid apron",
"tea towel sash", "waist ribbon", "corset belt",
"pearl belt", "star belt", "moon belt",
"bat wing capelet", "angel wing capelet", "plush tail charm",
"constellation shawl", "crystal rosary", "moon phase bracelet",
"galaxy scarf", "flower anklet", "tea cup earrings"
  ],

  specialTraits: [
"glows softly under moonlight",
"has constellation freckles",
"leaves tiny sparkles when excited",
"can summon warm drinks",
"has a tail shaped like a dessert",
"speaks to plushies like they are alive",
"changes eye color with mood",
"always smells faintly like vanilla",
"wings shimmer like stained glass",
"hair floats slightly when using magic",
"has star-shaped pupils",
"glows brighter when happy",
"leaves flower petals behind when running",
"can create tiny rain clouds",
"always feels pleasantly warm",
"has naturally glittery tears",
"can understand animals",
"can speak with spirits",
"giggles cause tiny stars to appear",
"footsteps leave glowing pawprints",
"hair changes color with the seasons",
"tail curls into a heart when excited",
"always smells like fresh pastries",
"has freckles that resemble galaxies",
"can summon tiny lantern wisps",
"horn glows when embarrassed",
"eyes sparkle in the dark",
"naturally attracts butterflies",
"flowers bloom around them when relaxed",
"voice sounds like wind chimes",
"can make tea taste better",
"can communicate with plushies",
"casts no reflection when sleepy",
"always finds lost things",
"has ears that twitch with emotions",
"tail poofs up when startled",
"can make plants grow faster",
"attracts fireflies at night",
"naturally warms cold blankets",
"leaves rainbow bubbles when laughing",
"can hear distant music nobody else hears",
"shadow moves independently when bored",
"always knows when it's going to rain",
"can make candles ignite with a snap",
"hair smells like lavender",
"wings shed glowing feathers",
"eyes resemble the night sky",
"can create floating hearts",
"laugh sounds like bells",
"never gets lost",
"can sense emotions through touch",
"always lands on their feet",
"can create tiny snowflakes indoors",
"has moon-shaped birthmarks",
"can understand babies and animals",
"voice echoes softly",
"can summon plush blankets",
"can make flowers change colors",
"naturally attracts cats",
"glows when hugged",
"tail changes shape with mood",
"can summon tiny stars",
"always smells like rain",
"hair sparkles after midnight",
"can speak every language in dreams",
"sleepwalks while floating",
"eyes become heart-shaped when excited",
"can hear whispers from old books",
"naturally attracts lucky charms",
"wings hum softly",
"creates warm cookies accidentally",
"can turn tears into crystals",
"has freckles that move like constellations",
"never catches a cold",
"can create tiny rainbows",
"always knows where the comfiest spot is",
"blush glows in the dark",
"has tiny fangs that show when smiling",
"can purr despite not being feline",
"tail sheds glitter when happy",
"hair becomes fluffy in the rain",
"can speak to flowers",
"has naturally cold hands",
"has naturally warm hands",
"can see hidden doors",
"can smell emotions like scents",
"voice changes with emotions",
"can create tiny shooting stars",
"naturally repels bugs",
"eyes glow during thunderstorms",
"can taste memories in tea",
"always smells like cinnamon",
"leaves snowflakes on mirrors",
"can create floating ribbons",
"can hear stars singing",
"tail wraps around friends protectively",
"creates tiny hearts while sleeping",
"hair becomes longer during winter",
"can summon moonflowers",
"glows softly when reading",
"never burns baked goods",
"can understand ghosts",
"can make stuffed animals move slightly",
"naturally attracts birds",
"can summon cozy sweaters",
"ears flop when sad",
"eyes resemble gemstones",
"creates tiny music notes when humming",
"can calm storms",
"always finds four-leaf clovers",
"can float a few inches when sleepy",
"always smells like strawberries",
"hair shines like silk",
"wings glow with emotions",
"can summon pillows",
"voice can soothe nightmares",
"naturally attracts good dreams",
"tail forms a question mark when curious",
"can summon tiny moons",
"laugh causes flowers to bloom",
"has tiny horns hidden in hair",
"eyes resemble stars in water",
"can create tiny marshmallows",
"always has perfect hair",
"can summon little clouds",
"shadow wags like a tail",
"hair glows at sunset",
"can see wishes being made",
"tail acts on its own",
"can understand old lullabies",
"always smells like hot chocolate",
"can create floating candles",
"wings become transparent in sunlight",
"eyes shimmer like opals",
"can see dream fragments",
"creates tiny butterflies when sneezing",
"has naturally rosy cheeks",
"can summon tea sets",
"voice sounds sweeter when singing",
"can hear moonlight",
"hair changes with phases of the moon",
"can summon tiny rabbits",
"leaves glowing footprints in snow",
"tail rings like a bell",
"can turn hugs into warmth",
"can weave dreams into blankets",
"can create tiny stars in drinks",
"naturally glows near loved ones",
"freckles twinkle when laughing",
"eyes become brighter when curious",
"can make rain smell sweeter",
"can tell fortunes through tea leaves",
"can summon star-shaped cookies",
"tail resembles whipped cream",
"wings look like flower petals",
"hair floats underwater",
"always smells faintly like coffee",
"can create tiny shooting hearts",
"can hear flowers growing",
"naturally attracts moon moths",
"voice echoes in dreams",
"can create floating books",
"can speak to candles",
"hair grows flowers when happy",
"eyes become pastel during spring",
"tail leaves sparkles on blankets",
"can create tiny suns",
"naturally attracts plushies",
"can sense forgotten memories",
"wings fold into a cape",
"can create tiny galaxies in bubbles",
"always knows when someone needs a hug",
"can summon sleepy clouds",
"hair glows during rainstorms",
"eyes shine like stained glass",
"creates tiny stars while baking",
"tail forms little hearts when cuddling",
"can make tea from moonlight",
"naturally smells like fresh bread",
"can create soft lullabies with magic",
"voice makes flowers sway",
"can store memories inside stars",
"freckles resemble tiny flowers",
"can create miniature auroras",
"eyes sparkle when telling stories",
"always leaves warmth behind",
"can see emotions as colors",
"tail becomes fluffy in winter",
"can summon tiny guardian wisps",
"radiates a calming aura"
  ],

  storyHooks: [
"Runs a tiny late-night dessert stall for magical creatures.",
"Inherited a mysterious cafe that only appears during rainstorms.",
"Collects lost wishes and turns them into tiny charms.",
"Designs outfits for spirits who want to visit the human world.",
"Keeps finding magical plushies abandoned on their doorstep.",
"Works at a bookstore where the books whisper secrets after midnight.",
"Is trying to save enough money to open a cozy tea shop.",
"Accidentally became the guardian of a sleepy little star sprite.",
"Makes enchanted sweets that reveal a person's happiest memory.",
"Travels between towns selling charms, snacks, and gentle advice.",

"Maintains a greenhouse where moonflowers only bloom for lonely hearts.",
"Delivers tea to ghosts who cannot leave their old homes.",
"Runs a flower cart with a mischievous fairy companion.",
"Can hear forgotten lullabies hidden inside old music boxes.",
"Works the night shift at a bakery frequented by dream spirits.",
"Repairs damaged plushies that secretly hold memories.",
"Searches antique shops for pieces of a missing constellation.",
"Paints portraits that occasionally come to life while nobody is watching.",
"Hosts weekly tea parties for shy forest spirits.",
"Owns a cat cafe where the cats are disguised familiars.",

"Receives letters addressed to people who haven't been born yet.",
"Helps stars find new places in the night sky.",
"Collects broken umbrellas and restores their magic.",
"Works at a moonlit aquarium filled with impossible creatures.",
"Can see the memories attached to lost jewelry.",
"Runs a cozy inn that only appears on foggy nights.",
"Has a pocket watch that stops whenever fate changes.",
"Finds abandoned dream journals in strange places.",
"Raises tiny cloud sheep in secret.",
"Is searching for the owner of a magical necklace.",

"Was gifted a lantern that attracts wandering souls.",
"Runs a bakery with recipes written by ghosts.",
"Delivers forgotten dreams to sleeping children.",
"Studies at a school hidden inside a giant library.",
"Keeps meeting the same mysterious traveler in different towns.",
"Adopted a tiny dragon that refuses to grow up.",
"Helps moon moths return home during the winter.",
"Inherited a doll shop that comes alive at midnight.",
"Works as a florist for weddings between magical beings.",
"Accidentally entered a contract with a sleepy moon spirit.",

"Collects sea glass that contains memories.",
"Protects a hidden shrine beneath the city.",
"Creates candles that reveal forgotten emotions.",
"Runs an arcade where every machine tells fortunes.",
"Finds old postcards from impossible places.",
"Helps lonely ghosts write letters to their loved ones.",
"Owns a train ticket that leads somewhere different every full moon.",
"Can hear wishes spoken to shooting stars.",
"Runs a tiny market stall during lantern festivals.",
"Searches for recipes left behind by their grandmother.",

"Was chosen by a stubborn little constellation spirit.",
"Keeps rescuing magical creatures from alleyways.",
"Owns a journal that writes back.",
"Works as a tailor for fairies and witches.",
"Can step into paintings while dreaming.",
"Is saving abandoned books from disappearing forever.",
"Delivers enchanted desserts on a bicycle.",
"Accidentally opened a portal inside their closet.",
"Can communicate with old stuffed animals.",
"Runs a bakery famous among moon rabbits.",

"Protects a garden hidden between seasons.",
"Collects tears that turn into crystals.",
"Finds mysterious gifts left on their windowsill.",
"Works at a tiny observatory on a mountain.",
"Can bake memories into cookies.",
"Is trying to reunite a family of lost spirits.",
"Owns a cafe visited by travelers from dreams.",
"Discovers tiny stars hiding inside old toys.",
"Can hear flowers gossiping with each other.",
"Maintains a lighthouse for wandering souls.",

"Was given the job of naming newborn stars.",
"Runs a secondhand shop filled with enchanted trinkets.",
"Searches for a mythical tea recipe.",
"Can see invisible doorways on rainy days.",
"Works as a guide for spirits visiting festivals.",
"Finds tiny notes hidden inside library books.",
"Accidentally befriended a shy ghost prince.",
"Owns a record player that plays forgotten songs.",
"Helps children recover lost dreams.",
"Protects a family recipe book with strange powers.",

"Can speak with creatures hiding in the clouds.",
"Runs a blanket shop loved by sleepy spirits.",
"Discovers magical messages in fortune cookies.",
"Is trying to restore an abandoned greenhouse.",
"Owns a collection of living postcards.",
"Travels with a wagon full of sweets and stories.",
"Finds stars that have fallen to Earth.",
"Works as a caretaker for tiny celestial creatures.",
"Can turn wishes into embroidery patterns.",
"Maintains a hidden moonflower garden for the royal family.",

"Has been tasked with delivering letters to forgotten gods.",
"Can hear stories hidden in seashells.",
"Runs a cozy inn for wandering witches.",
"Searches for the creator of a mysterious plush rabbit.",
"Finds magical recipe cards in random places.",
"Owns a tiny apartment shared with several spirits.",
"Can calm nightmares with handmade tea blends.",
"Travels the countryside restoring abandoned shrines.",
"Was entrusted with a key that opens impossible places.",
"Dreams of opening the warmest little cafe in the world."
  ]
};
