const DATA = {
  nameStarts: [
   "Lumi", "Nova", "Mira", "Sera", "Fae", "Astra", "Cinna", "Mochi",
"Vel", "Nyla", "Rosie", "Coco", "Elli", "Pippa", "Junie", "Kira",
"Luna", "Nori", "Emi", "Rumi", "Mimi", "Lila", "Zuri", "Opal",
"Fina", "Ari", "Rina", "Melo", "Yumi", "Taffy", "Bunni", "Lottie",
"Skye", "Tori", "Maple", "Sunny", "Peony", "Winnie", "Lacey", "Mika",
"Nixi", "Bree", "Dottie", "Rika", "Pixi", "Honey", "Daisy", "Maru",
"Suki", "Koko", "Finae", "Auri", "Kiki", "Mello", "Riri", "Starry",
"Airi", "Luma","Vivi", "Momo", "Nini", "Poki", "Chai", "Lyra", "Runa", "Noa",
"Eira", "Miri", "Fifi", "Tina", "Kona", "Sora", "Yuki", "Aika",
"Remi", "Rory", "Tali", "Miri", "Nene", "Lulu", "Sukiya", "Mirae",
"Anya", "Ririi", "Puri", "Mikae", "Sena", "Vela", "Liora", "Niva",
"Ayla", "Ceri", "Eirae", "Nixie", "Mikai", "Fiora", "Ciel", "Rhea",
"Ami", "Nia", "Penny", "Tika", "Vani", "Mallow", "Dewi", "Sola",
"Aurii", "Clover"
  ],

  nameEnds: [
    "belle", "luna", "rose", "star", "mimi", "bean", "wyn", "elle",
    "berry", "whisk", "bloom", "sprout", "mara", "shine", "puff", "moon", "elle", "ella", "ina", "inae", "ira", "irae", "ara", "arae",
"ora", "oria", "orae", "una", "unae", "ika", "ikae", "ikaa",
"ikai", "ikae", "ikaa", "ikaia", "ikaine", "ikaelle", "ikaira", "ikaora",
"ette", "etta", "etti", "ettia", "lyn", "lynn", "line", "lina",
"lene", "lena", "lise", "lisa", "ria", "rielle", "riel", "riellea",
"rina", "rinae", "rinae", "rinaelle", "rinaira", "rinaora", "risa", "rissa",
"mie", "mia", "mina", "mira", "mirae", "mielle", "mila", "milia",
"nelle", "nellea", "nette", "netta", "nina", "nia", "nielle", "niellea",
"yuki", "yuna", "yume", "yori", "yora", "yelle", "yette", "yina",
"ettea", "ellie", "ellia", "eena", "eira", "eirae", "eila", "eille",
"belle", "bella", "blossom", "berry", "bun", "bean", "boo", "pop",
"puff", "petal", "peach", "pie", "sprout", "song", "shine", "star",
"moon", "dream", "whisp", "mist", "dew", "dove", "kiss", "heart",
"tail", "wing", "leaf", "bloom", "drop", "cloud"
  ],

  surnames: [
    "Moonwhisk", "Starfall", "Velvetbrew", "Sweetspark", "Duskgarden",
    "Cloudberry", "Nightbloom", "Sugarveil", "Lavenderlace", "Coffeebean", "Starfall", "Moonwhisper", "Dewdrop", "Cloudberry", "Honeybell", "Rosebloom", "Willowmere", "Lavender",
"Starlight", "Moonvale", "Petalbrook", "Sunpetal", "Dreamleaf", "Snowbell", "Mapledew", "Rosethorn",
"Silvermist", "Skydancer", "Meadowlark", "Softwind", "Starweaver", "Moonweaver", "Rainblossom", "Sweetbriar",
"Fernbrook", "Cherryvale", "Berrybloom", "Moonflower", "Starling", "Hazelgrove", "Ivydream", "Pinewhisper",
"Cloudsong", "Lilacbreeze", "Honeyfield", "Rosewater", "Mistvale", "Dreamsong", "Sunwillow", "Peachgrove",
"Frostpetal", "Daisybrook", "Cloverfield", "Meadowshade", "Starbloom", "Mooncrest", "Willowshade", "Bloomheart",
"Softpetal", "Silverbrook", "Mosswhisper", "Foxglove", "Riversong", "Moonbrook", "Dewwhisper", "Starglade",
"Rainwhisper", "Hazelmist", "Skymallow", "Velvetrose", "Suncrest", "Mooncrest", "Starcrest", "Morningshade",
"Everdew", "Petalsong", "Wildbloom", "Willowbloom", "Meadowmist", "Cloudwhisper", "Honeydew", "Snowbloom",
"Maplewhisper", "Roselight", "Berrysong", "Lilybrook", "Starbrook", "Moonbrook", "Softbrook", "Rainbrook",
"Peachblossom", "Honeyblossom", "Lilacgrove", "Sagefield", "Morningdew", "Dreamwillow", "Silverleaf", "Fernsong",
"Roseveil", "Moonveil", "Starveil", "Skylark", "Fawnheart", "Amberfield", "Cinnamonvale", "Sugarbloom",
"Moonhaven", "Starhaven", "Cloudhaven", "Willowhaven", "Rosehaven", "Meadowhaven", "Berryhaven", "Honeyhaven",
"Sunhaven", "Dreamhaven", "Mistbloom", "Moonpetal", "Starpetal", "Rosedream", "Skydream", "Fernvale",
"Maplevale", "Lilacvale", "Cloudvale", "Peachvale", "Honeyvale", "Snowvale", "Rosegrove", "Moonshade",
"Starshade", "Berryshade", "Petalshade", "Willowgrove", "Silvergrove", "Dawnwhisper", "Twilightbloom", "Dreammist",
"Moonmist", "Starmist", "Rosemist", "Peachmist", "Cloudmist", "Silvermist", "Honeymist", "Berrymist",
"Sunmist", "Dewmist", "Mallowbrook", "Sugarbrook", "Velvetbrook", "Lacefield", "Ivoryvale", "Snowberry",
"Moonberry", "Starberry", "Honeyberry", "Peachberry", "Roseberry", "Cloverberry", "Dreamberry", "Cloudberry",
"Moonsong", "Starsong", "Rosesong", "Willowsong", "Dreamsong", "Silversong", "Skysong", "Berrysong",
"Petalheart", "Moonheart", "Starheart", "Roseheart", "Honeyheart", "Dreamheart", "Silverheart", "Sunheart",
"Cloudheart", "Willowheart", "Fawnsong", "Meadowheart", "Snowheart", "Bloomsong", "Softsong", "Lavenderfield",
"Goldenleaf", "Autumnbloom", "Summerdew", "Springwhisper", "Winterrose", "Crescentvale", "Celestine", "Moonridge",
"Starridge", "Rosemeadow", "Honeymeadow", "Cloudmeadow", "Dreammeadow", "Petalmeadow", "Willowmeadow", "Silverbell",
"Moonbell", "Starbell", "Rosebell", "Berrybell", "Honeybell", "Snowbell", "Dreambell", "Cloudbell"
  ],

  species: [
   "Bunny", "Bat", "Bear", "Red Panda", "Coffee Fox", "Cloud Cat",
"Unicorn", "Panda", "Canine", "Cow", "Dragon Bunny", "Alien Bun",
"Deer", "Capybara", "Raccoon", "Cat", "Dog", "Wolf", "Fox",
"Fennec Fox", "Arctic Fox", "Otter", "Ferret", "Pine Marten", "Weasel",
"Mouse", "Rat", "Hamster", "Guinea Pig", "Chinchilla", "Hedgehog",
"Skunk", "Possum", "Squirrel", "Chipmunk", "Beaver", "Badger",
"Raccoon Dog", "Tanuki", "Coyote", "Jackal", "Hyena", "Lion",
"Tiger", "Leopard", "Panther", "Snow Leopard", "Lynx", "Bobcat",
"Cheetah", "Cougar", "Jaguar", "Serval", "Caracal", "Pallas Cat",
"Goat", "Sheep", "Alpaca", "Llama", "Horse", "Pony",
"Donkey", "Pig", "Boar", "Moose", "Elk", "Reindeer",
"Gazelle", "Antelope", "Buffalo", "Bison", "Yak", "Camel",
"Giraffe", "Elephant", "Hippo", "Tapir", "Sloth", "Koala",
"Kangaroo", "Wallaby", "Quokka", "Platypus", "Wombat", "Armadillo",
"Seal", "Sea Lion", "Dolphin", "Whale", "Shark", "Axolotl",
"Frog", "Salamander", "Gecko", "Chameleon", "Snake", "Turtle",
"Alligator", "Crocodile", "Dragon", "Eastern Dragon", "Sea Dragon", "Fairy Dragon",
"Kirin", "Qilin", "Pegasus", "Griffin", "Jackalope", "Kitsune",
"Wolpertinger", "Moth Cat", "Star Bunny", "Moon Bat", "Sun Lion",
"Cloud Sheep", "Dream Deer", "Galaxy Wolf", "Cosmic Fox", "Candy Bear",
"Strawberry Cow", "Mochi Bunny", "Boba Cat", "Cookie Panda", "Marshmallow Fox",
"Pastel Deer", "Crystal Unicorn", "Moon Rabbit", "Tea Raccoon", "Lantern Goat",
"Plush Dragon", "Candle Cat", "Jelly Bunny", "Velvet Bat", "Star Panda",
"Fawn Dog", "Honey Bear", "Sakura Fox", "Celestial Deer", "Nebula Cat",
"Coffee Cat", "Matcha Bunny", "Taiyaki Fox", "Dango Deer", "Cake Bat",
"Galaxy Bunny", "Space Otter", "Alien Cat", "Void Fox", "Dream Panda",
"Cloud Bunny", "Sunflower Deer", "Rose Goat", "Mushroom Raccoon", "Pumpkin Bear",
"Moon Fox", "Star Sheep", "Aurora Wolf", "Comet Cat", "Spirit Deer"
  ],

  themes: [
    "Strawberry Cafe", "Moonlit Bakery", "Celestial Gothic", "Pastel Arcade",
"Cozy Rainy-Day Bookstore", "Magic Flower Stall", "Candy Witch",
"Dreamy Sleepover", "Starry Coffeehouse", "Autumn Harvest Market",
"Kawaii Seamstress", "Gothic Tea Party", "Cherry Blossom Festival",
"Moonflower Garden", "Cloudy Tea House", "Cozy Library", "Sunset Beach Cafe",
"Plushie Collector", "Sweet Lolita", "Galaxy Aquarium", "Fairy Tailor",
"Vintage Bakery", "Moon Rabbit Shrine", "Star Festival", "Bubble Tea Shop",
"Cottagecore Farm", "Pumpkin Patch", "Rainy Train Station", "Magical Florist",
"Crystal Cavern", "Dreamy Pajama Party", "Forest Apothecary", "Witch's Kitchen",
"Pastel Carnival", "Moonlight Picnic", "Cozy Cat Cafe", "Candy Shop",
"Enchanted Toy Store", "Ice Cream Parlor", "Cookie Bakery", "Sunflower Meadow",
"Celestial Observatory", "Star Gazing Club", "Night Market", "Lantern Festival",
"Book Nook Cafe", "Sleepy Village", "Rainy Day Diner", "Moonlit Alley",
"Magical Aquarium", "Vintage Arcade", "Gothic Boutique", "Mushroom Cottage",
"Tea Garden", "Cloud Kingdom", "Dreamcore Bedroom", "Moonlit Forest",
"Cherry Tea Shop", "Starry Bedroom", "Coastal Boardwalk", "Seaside Bakery",
"Fantasy Inn", "Wizard Library", "Potion Shop", "Crystal Garden",
"Moon Cafe", "Cloud Bakery", "Candy Kingdom", "Sakura Festival",
"Forest Cabin", "Lavender Fields", "Cozy Fireplace", "Sunrise Meadow",
"Moonlight Ballroom", "Royal Tea Room", "Fairy Market", "Kawaii Idol",
"Pastel Princess", "Gothic Princess", "Moon Shrine", "Starlight Theater",
"Dream Journal", "Plush Workshop", "Handmade Crafts", "Knitting Club",
"Tea Time Picnic", "Cookie Decorating", "Rainy Window Seat", "Moonlit Rooftop",
"Star Bakery", "Celestial Library", "Rose Garden", "Lily Pond",
"Flower Crown Shop", "Vintage Tailor", "Crystal Boutique", "Sweet Café Date",
"Nighttime Carnival", "Cozy Campsite", "Winter Market", "Spring Festival",
"Summer Fireflies", "Autumn Leaves", "Snowy Village", "Rainy City Lights",
"Moon Jellyfish Aquarium", "Galaxy Planetarium", "Dreamy Bedroom", "Pastel Kitchen",
"Sunrise Cafe", "Moonrise Diner", "Bunny Bakery", "Fox Tea House",
"Bear Honey Shop", "Deer Flower Farm", "Cloud Observatory", "Star Fountain",
"Moon Garden", "Sunflower Cafe", "Rainy Bus Stop", "Vintage Record Store",
"Cozy Reading Corner", "Art Studio", "Paint Night", "Scrapbook Club",
"Pottery Studio", "Embroidery Circle", "Crochet Club", "Candle Shop",
"Perfume Boutique", "Jewelry Store", "Antique Market", "Magic School",
"Witch Academy", "Fairy Classroom", "Dragon Library", "Moon Cathedral",
"Gothic Cathedral", "Rose Manor", "Victorian Tea Room", "Haunted Mansion",
"Ghost Cafe", "Moonlit Cemetery", "Pumpkin Bakery", "Candy Manor",
"Celestial Palace", "Dream Palace", "Royal Garden", "Cherry Orchard",
"Blueberry Farm", "Strawberry Festival", "Peach Orchard", "Honey Farm",
"Bee Keeper Cottage", "Moonflower Conservatory", "Cloud Palace", "Star Observatory",
"Fairy Ring", "Mushroom Village", "Moon Bunny Burrow", "Plush Kingdom",
"Cozy Blanket Fort", "Dream Sleepover", "Movie Marathon Night", "Board Game Cafe",
"Video Game Arcade", "Retro Arcade", "Magical Arcade", "Kawaii Maid Cafe",
"Gothic Maid Cafe", "Boba Tea Shop", "Milkshake Bar", "Pastry Shop",
"Chocolate Factory", "Candy Factory", "Moonlight Harbor", "Rainy Harbor Town",
"Fishing Village", "Beach Festival", "Ocean Aquarium", "Coral Garden",
"Crystal Beach", "Mermaid Lagoon", "Starry Planetarium", "Galaxy Museum",
"Moon Museum", "Art Gallery", "Photo Studio", "Music Room",
"Piano Lounge", "Jazz Cafe", "Moonlight Concert", "Star Idol Stage",
"Flower Festival", "Lantern Parade", "Cherry Moon Festival", "Cosmic Carnival",
"Tea Witch Cottage", "Moon Mage Tower", "Sun Mage Tower", "Celestial Chapel",
"Dream Bakery", "Star Weaver Studio", "Magic Quilt Shop", "Pastel Toy Shop",
"Rainy Flower Shop", "Moonlit Greenhouse", "Cloud Nursery", "Sunset Rooftop Garden",
"Cat Nap Cafe", "Foxfire Tavern", "Cozy Attic Bedroom", "Star Nursery",
"Fairy Bakery", "Lavender Tea House", "Moonflower Bookstore", "Celestial Sewing Room"
  ],

  palettes: [
   "Dusty pink, cream, espresso brown",
"Lavender, black, silver",
"Baby blue, cloud white, soft gold",
"Chocolate brown, rose pink, vanilla",
"Mint, peach, warm cream",
"Deep purple, magenta, moonlight silver",
"Pastel rainbow, white, candy pink",
"Forest green, honey yellow, warm brown",
"Sky blue, lavender, pearl white",
"Sage green, cream, dusty rose",
"Strawberry pink, milk white, cocoa brown",
"Moonlight blue, silver, midnight navy",
"Peach, coral, warm ivory",
"Mint green, white, pale yellow",
"Soft lilac, blush pink, cream",
"Black, crimson, silver",
"Plum purple, charcoal, lavender",
"Rose gold, ivory, champagne",
"Sunflower yellow, sage green, cream",
"Ocean blue, seafoam, sandy beige",
"Teal, peach, white",
"Sky blue, lemon yellow, white",
"Ruby red, black, gold",
"Emerald green, cream, copper",
"Periwinkle, pink, white",
"Coffee brown, caramel, cream",
"Soft orange, honey, vanilla",
"Lavender, mint, baby pink",
"Cotton candy pink, aqua, white",
"Storm gray, silver, icy blue",
"Wine red, blush pink, black",
"Pastel yellow, mint, lavender",
"Powder blue, silver, white",
"Coral pink, cream, mocha",
"Midnight blue, violet, silver",
"Sakura pink, white, pale green",
"Chocolate, cream, strawberry pink",
"Berry purple, blush, cream",
"Rose red, black, ivory",
"Honey gold, cream, cinnamon",
"Seafoam green, sky blue, white",
"Lilac, silver, moon white",
"Baby pink, lavender, mint",
"Peach cream, cocoa, rose pink",
"Sunset orange, coral, cream",
"Indigo, silver, pale lavender",
"Forest green, cream, amber",
"Blueberry blue, cream, lilac",
"Warm beige, caramel, espresso",
"Cloud gray, baby blue, white",
"Rose pink, mauve, cream",
"Mint green, cocoa brown, vanilla",
"Silver, navy, moon blue",
"Soft red, cream, dusty pink",
"Pumpkin orange, sage green, cream",
"Black, purple, rose gold",
"Golden yellow, white, honey brown",
"Sky blue, mint, cream",
"Bubblegum pink, white, pale blue",
"Maroon, black, gold",
"Teal, navy, silver",
"Strawberry pink, cream, mint",
"Mocha brown, dusty rose, ivory",
"Peach, lavender, white",
"Pastel blue, lemon, pink",
"Dark green, copper, beige",
"Coral, aqua, white",
"Periwinkle, cream, pale gold",
"Rose pink, pearl white, silver",
"Chocolate brown, vanilla, caramel",
"Black, crimson, moon silver",
"Sage green, peach, cream",
"Blue gray, silver, white",
"Deep teal, pale gold, ivory",
"Plum purple, pink, cream",
"Cherry red, black, white",
"Cloud white, baby pink, lavender",
"Honey yellow, cream, soft orange",
"Emerald green, gold, black",
"Peach pink, warm white, cocoa",
"Sky blue, moon silver, navy",
"Mint green, white, pastel pink",
"Lilac purple, cream, silver",
"Rosewood, blush pink, ivory",
"Caramel, cream, honey gold",
"Blueberry, lavender, cream",
"Black, silver, wine red",
"Sea blue, white, coral",
"Pastel mint, peach, white",
"Strawberry red, cream, chocolate",
"Moon blue, lavender, silver",
"Sage green, ivory, mocha",
"Cloud white, pale yellow, blue",
"Magenta, deep purple, silver",
"Rose gold, blush, cream",
"Sky blue, lilac, white",
"Espresso brown, cream, soft pink",
"Sunflower yellow, peach, cream",
"Periwinkle, pink, mint",
"Charcoal gray, lavender, silver",
"Coral pink, white, gold",
"Baby blue, silver, lavender",
"Cinnamon brown, cream, blush",
"Forest green, beige, amber",
"Mint, ivory, pale gold",
"Chocolate brown, cherry red, cream",
"Rose pink, white, soft gray",
"Moonlight silver, navy, pale blue",
"Strawberry milk pink, cream, cocoa",
"Lemon yellow, white, mint",
"Royal purple, black, silver",
"Soft aqua, white, pearl",
"Honey gold, mocha, cream",
"Blush pink, sage green, ivory",
"Blue lavender, white, silver",
"Rose red, cream, champagne",
"Midnight navy, silver, lavender",
"Peach, strawberry pink, vanilla",
"Soft green, cream, honey",
"Baby pink, white, pale yellow",
"Berry purple, moon silver, black",
"Cloud blue, cream, lavender",
"Mint, blush pink, white",
"Copper, cream, espresso",
"Coral orange, pale yellow, white",
"Periwinkle blue, pearl, pink",
"Rosewood red, gold, cream",
"Sky blue, cloud gray, white",
"Chocolate brown, vanilla cream, pink",
"Lavender, moon blue, silver",
"Forest moss, honey, cream",
"Candy pink, pastel blue, white",
"Teal green, cream, peach",
"Midnight purple, silver, black",
"Peach cream, dusty rose, ivory",
"Baby blue, mint, white",
"Warm caramel, cream, coffee brown",
"Rose quartz pink, silver, white",
"Seafoam green, ivory, pale blue",
"Crimson, black, silver",
"Plum, blush pink, cream",
"Honey yellow, sage, beige",
"Pastel rainbow, pearl white, lavender",
"Soft coral, vanilla, cocoa",
"Moonlight blue, cloud white, silver",
"Espresso brown, cream, caramel",
"Sakura pink, pearl, mint",
"Storm gray, navy, silver",
"Mint green, pale peach, ivory",
"Rose pink, chocolate brown, cream",
"Sunset peach, lavender, white",
"Berry blue, silver, white",
"Warm cream, honey gold, brown",
"Black, plum, rose gold",
"Sky blue, pale lavender, pearl",
"Forest green, cream, cinnamon",
"Blueberry purple, pink, white",
"Vanilla cream, blush, caramel",
"Deep navy, moon silver, white",
"Peach pink, mint green, cream",
"Cherry blossom pink, white, gold",
"Teal blue, silver, ivory",
"Soft yellow, cream, peach",
"Rose red, black, moon silver",
"Baby blue, cotton pink, white",
"Sage green, dusty rose, cream",
"Chocolate brown, strawberry pink, vanilla",
"Lavender gray, silver, white",
"Sunflower yellow, honey brown, cream",
"Mint blue, white, silver",
"Pastel peach, lilac, cream",
"Forest green, amber, ivory",
"Deep purple, pink, silver",
"Pearl white, blush pink, champagne",
"Caramel brown, cream, rose",
"Sky blue, moon white, pale gold",
"Seafoam, mint, ivory",
"Black, magenta, silver",
"Berry pink, cream, mocha",
"Cloud white, baby blue, lavender",
"Honey gold, cream, sage green",
"Rosewood, blush, moon silver",
"Bluebell blue, white, pink",
"Espresso brown, vanilla, honey",
"Peach, coral pink, ivory",
"Midnight blue, lavender, moon silver"
  ],

  personalities: [
    "soft-spoken", "dramatic", "bratty", "motherly", "mischievous",
"sleepy", "spoiled", "loyal", "chaotic", "gentle", "protective",
"curious", "flirty", "bookish", "clumsy", "confident",
"shy", "timid", "bashful", "playful", "cheerful", "optimistic",
"pessimistic", "sarcastic", "witty", "goofy", "energetic", "hyper",
"laid-back", "easygoing", "reserved", "quiet", "talkative", "bubbly",
"affectionate", "clingy", "attention-seeking", "stubborn", "determined",
"independent", "dependable", "caring", "nurturing", "patient",
"impatient", "romantic", "dreamy", "creative", "artistic", "musical",
"organized", "messy", "scatterbrained", "forgetful", "responsible",
"mature", "childish", "whimsical", "eccentric", "elegant", "graceful",
"awkward", "anxious", "worry-prone", "sensitive", "empathetic",
"compassionate", "kind-hearted", "selfless", "selfish", "vain",
"vain-but-sweet", "fashionable", "stylish", "trendy", "old-fashioned",
"traditional", "rebellious", "free-spirited", "adventurous",
"cautious", "carefree", "reckless", "bold", "fearless", "cowardly",
"competitive", "cooperative", "helpful", "supportive", "observant",
"analytical", "logical", "emotional", "passionate", "fiery",
"hot-headed", "calm", "collected", "stoic", "mysterious",
"secretive", "honest", "blunt", "polite", "well-mannered",
"sassy", "snarky", "teasing", "friendly", "welcoming",
"charismatic", "charming", "sweet", "innocent", "naive",
"street-smart", "clever", "resourceful", "hardworking", "lazy",
"sleep-loving", "foodie", "tea-loving", "coffee-obsessed",
"workaholic", "perfectionist", "ambitious", "content", "humble",
"prideful", "grumpy", "tsundere", "kuudere", "yandere",
"deredere", "airheaded", "ditzy", "gullible", "trusting",
"suspicious", "guarded", "protective-big-sibling", "mother-hen",
"big-hearted", "gentle giant", "tiny menace", "gremlin",
"chaos goblin", "prankster", "joker", "class clown",
"daydreamer", "starry-eyed", "hopeful", "sentimental", "nostalgic",
"melancholic", "brooding", "gothic", "spooky", "witchy",
"nature-loving", "animal-loving", "bookworm", "scholarly",
"intellectual", "nerdy", "tech-savvy", "crafty", "resourceful",
"perceptive", "intuitive", "wise", "motherly-but-strict",
"gentle-but-firm", "soft-hearted", "forgiving", "vengeful",
"jealous", "possessive", "devoted", "faithful", "protective-big-brother",
"protective-big-sister", "clingy-but-caring", "shameless",
"dramatic-princess", "spoiled-princess", "cozy", "homebody",
"social butterfly", "introverted", "extroverted", "ambiverted",
"adorkable", "excitable", "curiosity-driven", "peaceful",
"serene", "radiant", "sunny", "moonlike", "starry-eyed",
"softie", "cinnamon-roll", "crybaby", "resilient", "tenacious",
"headstrong", "gentle soul", "warm-hearted", "lovable menace",
"unapologetically herself", "surprisingly nurturing"
  ],

  occupations: [
 "barista", "florist", "librarian", "potion seller", "plushie maker",
"night bakery assistant", "fashion designer", "cafe owner",
"fortune teller", "arcade attendant", "jewelry apprentice",
"traveling snack vendor", "baker", "pastry chef", "tea shop owner",
"bookstore clerk", "toy maker", "candlemaker", "tailor",
"seamstress", "dressmaker", "embroidery artist", "crochet artist",
"knitting instructor", "ceramic artist", "potter", "painter",
"illustrator", "comic artist", "tattoo artist", "graphic designer",
"calligrapher", "scrapbook artist", "sticker designer", "plush repairer",
"doll maker", "toy collector", "stationery designer", "journal maker",
"perfumer", "soap maker", "flower arranger", "gardener",
"greenhouse keeper", "herbalist", "tea blender", "beekeeper",
"honey farmer", "fruit picker", "jam maker", "cheesemaker",
"chocolatier", "ice cream vendor", "candy maker", "ramen chef",
"sushi chef", "food truck owner", "street vendor", "picnic planner",
"wedding planner", "party decorator", "event coordinator",
"festival organizer", "maid cafe hostess", "cat cafe manager",
"animal shelter worker", "pet groomer", "dog trainer",
"veterinary assistant", "aquarium caretaker", "bird sanctuary keeper",
"horse trainer", "stable hand", "rancher", "farmer",
"shepherd", "fisher", "boat captain", "lighthouse keeper",
"park ranger", "forest guide", "camp counselor", "tour guide",
"museum curator", "art gallery owner", "historian", "archivist",
"researcher", "teacher", "tutor", "professor",
"kindergarten teacher", "music teacher", "dance instructor",
"piano instructor", "choir director", "violinist", "cellist",
"singer", "idol", "voice actor", "radio host",
"podcaster", "news reporter", "photographer", "videographer",
"filmmaker", "streamer", "game developer", "programmer",
"web designer", "app developer", "robotics engineer", "inventor",
"clockmaker", "watchmaker", "jeweler", "gem cutter",
"blacksmith", "silversmith", "woodworker", "carpenter",
"furniture maker", "architect", "interior designer", "landscape designer",
"real estate agent", "hotel receptionist", "innkeeper",
"bed and breakfast owner", "housekeeper", "butler", "maid",
"babysitter", "nanny", "caregiver", "nurse",
"doctor", "dentist", "pharmacist", "therapist",
"counselor", "life coach", "yoga instructor", "fitness trainer",
"masseuse", "spa attendant", "makeup artist", "hair stylist",
"nail artist", "esthetician", "fashion model", "costume designer",
"cosplayer", "stage actor", "circus performer", "magician",
"puppeteer", "storyteller", "author", "poet",
"novelist", "translator", "editor", "bookbinder",
"mail carrier", "courier", "train conductor", "bus driver",
"taxi driver", "delivery driver", "mechanic", "electrician",
"plumber", "firefighter", "police officer", "security guard",
"astronomer", "planetarium guide", "weather reporter",
"cloud researcher", "dream analyst", "star chart maker",
"fortune cookie writer", "tarot reader", "crystal shop owner",
"witch", "moon priestess", "temple caretaker", "shrine maiden",
"dragon caretaker", "fairy researcher", "spellbook librarian",
"magic teacher", "wand maker", "rune engraver",
"potion brewer", "alchemist", "enchanter", "magic tailor",
"monster veterinarian", "griffin stable keeper", "cloud shepherd",
"lantern maker", "starweaver", "dream catcher artisan",
"moonflower gardener", "festival lantern seller", "tea witch",
"candy witch", "traveling bard", "treasure hunter",
"antique dealer", "pawn shop owner", "clock tower keeper",
"observatory assistant", "cat sitter", "plush collector",
"board game cafe host", "arcade owner", "bubble tea maker",
"cozy inn owner", "flower cart vendor", "pastry decorator",
"cake artist", "moonlight market vendor", "jelly maker",
"fortune cookie baker", "seashell collector", "postcard illustrator"
  ],

  aesthetics: [
    "pastel goth", "cozy cottagecore", "celestial kawaii", "soft gothic",
"candycore", "dreamy cafe", "moon witch", "storybook cute",
"rainy-day cozy", "starry streetwear", "sweet lolita", "sleepy plushcore",
"fairycore", "angelcore", "dreamcore", "kidcore",
"softcore", "cloudcore", "mooncore", "starcore",
"spacecore", "galaxycore", "sunsetcore", "sunrisecore",
"berrycore", "strawberrycore", "peachcore", "lavendercore",
"honeycore", "teacore", "coffeecore", "bakerycore",
"bunnycore", "catcore", "foxcore", "bearcore",
"deercore", "pandacore", "batcore", "dragoncore",
"forestcore", "mushroomcore", "flowercore", "gardencore",
"rosecore", "lilycore", "sunflowercore", "ivycore",
"sakuracore", "meadowcore", "raincore", "stormcore",
"mistcore", "snowcore", "wintercore", "autumncore",
"springcore", "summercore", "nightcore", "twilightcore",
"midnightcore", "moonlit cottagecore", "vintage bakery", "tea party chic",
"victorian gothic", "gothic lolita", "classic lolita", "princesscore",
"royalcore", "fairytalecore", "storybook whimsy", "storybook fantasy",
"plushcore", "toycore", "sanriocore", "kawaiicore",
"bubblegum pop", "cotton candycore", "jellycore", "dessertcore",
"cookiecore", "chocolatecore", "marshmallowcore", "ice creamcore",
"boba tea aesthetic", "maid cafe", "arcade pastel", "retro kawaii",
"retro arcade", "y2k pastel", "yume kawaii", "decora kei",
"harajuku cute", "pastel streetwear", "goth streetwear", "star idol",
"idolcore", "magical girl", "witchcore", "tea witch",
"candy witch", "moon priestess", "celestial witch", "crystal witch",
"tarotcore", "potioncore", "alchemycore", "fantasy academia",
"light academia", "dark academia", "bookworm chic", "librarycore",
"rainy bookstore", "cozy library", "journalcore", "stationerycore",
"scrapbookcore", "craftcore", "crochetcore", "knittingcore",
"embroiderycore", "sewingcore", "artsy pastel", "paintcore",
"musiccore", "pianocore", "vinylcore", "jazz lounge",
"coffeehouse chic", "cat cafe", "bunny cafe", "flower shop aesthetic",
"greenhousecore", "apothecarycore", "candlecore", "perfumecore",
"spa aesthetic", "cozy pajamas", "sleepovercore", "blanket fort",
"pillow princess", "cozy gamer", "streamercore", "deskcore",
"plant mom aesthetic", "homebody chic", "minimal kawaii", "soft minimalism",
"vintage pastel", "retro diner", "retro sweetheart", "polaroidcore",
"lacecore", "ribboncore", "pearlcore", "rose gold aesthetic",
"moonlight elegance", "silver celestial", "velvet gothic", "black lace",
"romantic gothic", "vampire chic", "gothic romance", "haunted elegance",
"ghostcore", "spooky cute", "pumpkincore", "halloween kawaii",
"coffin cute", "batty pastel", "midnight garden", "enchanted forest",
"fairy garden", "cottage witch", "elfcore", "faecore",
"mermaidcore", "seacore", "aquariumcore", "shellcore",
"coral pastel", "beach cottage", "boardwalk retro", "coastal grandma",
"coastal cute", "sunflower picnic", "picniccore", "campfire cozy",
"lantern festival", "night market", "festivalcore", "fireflycore",
"cloud kingdom", "dream palace", "celestial palace", "princess bedroom",
"nurserycore", "babycore", "teddybearcore", "plush collector",
"cozy attic", "atticcore", "moon bunny aesthetic", "star bunny aesthetic",
"nebula chic", "cosmic dreamcore", "constellationcore", "auroracore",
"crystalcore", "gemcore", "opalcore", "moonstone elegance",
"honey bee cottagecore", "lavender fields", "rainy window aesthetic",
"warm fireplace", "tea and books", "soft celestial", "moonflower chic",
"sleepy sunday", "cozy rainy cafe", "starlight elegance", "pastel celestial"
  ],

  accessories: [
  "crescent moon hair clips", "oversized hoodie", "tiny star purse",
"heart-shaped glasses", "ribbon collar", "plush backpack",
"coffee cup charm", "lace gloves", "strawberry earrings",
"spellbook satchel", "fluffy slippers", "moon pendant", "star pendant", "sun pendant", "heart locket",
"locket necklace", "charm bracelet", "friendship bracelet",
"pearl bracelet", "lace choker", "ribbon choker",
"bell collar", "bow tie collar", "gem collar",
"flower crown", "rose crown", "sunflower crown",
"moon tiara", "crystal tiara", "star headband",
"cat ear headband", "bunny ear headband", "bat wing headband",
"halo headpiece", "lace bonnet", "beret",
"knitted beanie", "pom-pom hat", "witch hat",
"sun hat", "straw hat", "newsboy cap",
"baseball cap", "hooded cape", "poncho",
"shawl", "lace shawl", "cardigan",
"cropped jacket", "oversized scarf", "fluffy scarf",
"plaid scarf", "leg warmers", "striped socks",
"knee-high socks", "lace stockings", "fishnet stockings",
"fingerless gloves", "mittens", "arm warmers",
"lace arm sleeves", "ribbon wrist cuffs", "bracelet stack",
"anklet", "toe ring", "promise ring",
"moonstone ring", "rose ring", "star ring",
"flower earrings", "moon earrings", "star earrings",
"heart earrings", "crystal earrings", "pearl earrings",
"mismatch earrings", "dangling earrings", "clip-on earrings",
"hair bows", "double hair bows", "ribbon scrunchie",
"star scrunchie", "flower hair pin", "butterfly clip",
"moon hair comb", "pearl hair chain", "braided ribbon",
"hair beads", "hair charms", "hair ribbon",
"hair flowers", "flower barrettes", "star barrettes",
"lace eyepatch", "round glasses", "gold-rim glasses",
"rose-tinted glasses", "moon sunglasses", "star sunglasses",
"tiny backpack", "mini purse", "crossbody bag",
"satchel", "messenger bag", "book bag",
"moon purse", "cloud purse", "bunny purse",
"bear purse", "cat purse", "bat purse",
"strawberry purse", "cake purse", "milk carton purse",
"potion bottle purse", "crescent moon purse", "plush purse",
"coin pouch", "wallet chain", "phone charm",
"star phone charm", "bunny phone charm", "strap keychain",
"plush keychain", "heart keychain", "flower keychain",
"tiny bell keychain", "lucky charm", "dreamcatcher charm",
"book charm", "tea cup charm", "moon charm",
"star charm", "sun charm", "cloud charm",
"rainbow charm", "berry charm", "cookie charm",
"cake charm", "ice cream charm", "boba charm",
"crochet tote", "canvas tote", "flower tote",
"moon tote", "star tote", "cat tote",
"bear tote", "bunny tote", "book tote",
"patchwork tote", "lace parasol", "frilly parasol",
"sun umbrella", "moon umbrella", "clear umbrella",
"flower umbrella", "star umbrella", "ribbon umbrella",
"tiny notebook", "journal", "sticker binder",
"scrapbook", "photo album", "bookmark tassel",
"bookmark charm", "mini sketchbook", "fountain pen",
"quill pen", "wax seal kit", "ink bottle necklace",
"pocket watch", "star pocket watch", "moon pocket watch",
"compact mirror", "heart mirror", "flower mirror",
"perfume atomizer", "lip balm holder", "makeup pouch",
"brush case", "travel case", "tea tin",
"cookie tin", "bento bag", "lunch tote",
"sleep mask", "moon sleep mask", "star sleep mask",
"plush neck pillow", "travel pillow", "blanket shawl",
"paw slippers", "bunny slippers", "bear slippers",
"moon slippers", "star slippers", "cloud slippers",
"rain boots", "lace-up boots", "platform shoes",
"mary janes", "ballet flats", "ribbon heels",
"moon heels", "star sneakers", "light-up sneakers",
"crystal brooch", "rose brooch", "bow brooch",
"star brooch", "moon brooch", "cameo brooch",
"lace apron", "frilly apron", "maid apron",
"tea towel sash", "waist ribbon", "corset belt",
"pearl belt", "star belt", "moon belt",
"bat wing capelet", "angel wing capelet", "plush tail charm",
"constellation shawl", "crystal rosary", "moon phase bracelet",
"galaxy scarf", "flower anklet", "tea cup earrings"
  ],

  specialTraits: [
"glows softly under moonlight",
"has constellation freckles",
"leaves tiny sparkles when excited",
"can summon warm drinks",
"has a tail shaped like a dessert",
"speaks to plushies like they are alive",
"changes eye color with mood",
"always smells faintly like vanilla",
"wings shimmer like stained glass",
"hair floats slightly when using magic",
"has star-shaped pupils",
"glows brighter when happy",
"leaves flower petals behind when running",
"can create tiny rain clouds",
"always feels pleasantly warm",
"has naturally glittery tears",
"can understand animals",
"can speak with spirits",
"giggles cause tiny stars to appear",
"footsteps leave glowing pawprints",
"hair changes color with the seasons",
"tail curls into a heart when excited",
"always smells like fresh pastries",
"has freckles that resemble galaxies",
"can summon tiny lantern wisps",
"horn glows when embarrassed",
"eyes sparkle in the dark",
"naturally attracts butterflies",
"flowers bloom around them when relaxed",
"voice sounds like wind chimes",
"can make tea taste better",
"can communicate with plushies",
"casts no reflection when sleepy",
"always finds lost things",
"has ears that twitch with emotions",
"tail poofs up when startled",
"can make plants grow faster",
"attracts fireflies at night",
"naturally warms cold blankets",
"leaves rainbow bubbles when laughing",
"can hear distant music nobody else hears",
"shadow moves independently when bored",
"always knows when it's going to rain",
"can make candles ignite with a snap",
"hair smells like lavender",
"wings shed glowing feathers",
"eyes resemble the night sky",
"can create floating hearts",
"laugh sounds like bells",
"never gets lost",
"can sense emotions through touch",
"always lands on their feet",
"can create tiny snowflakes indoors",
"has moon-shaped birthmarks",
"can understand babies and animals",
"voice echoes softly",
"can summon plush blankets",
"can make flowers change colors",
"naturally attracts cats",
"glows when hugged",
"tail changes shape with mood",
"can summon tiny stars",
"always smells like rain",
"hair sparkles after midnight",
"can speak every language in dreams",
"sleepwalks while floating",
"eyes become heart-shaped when excited",
"can hear whispers from old books",
"naturally attracts lucky charms",
"wings hum softly",
"creates warm cookies accidentally",
"can turn tears into crystals",
"has freckles that move like constellations",
"never catches a cold",
"can create tiny rainbows",
"always knows where the comfiest spot is",
"blush glows in the dark",
"has tiny fangs that show when smiling",
"can purr despite not being feline",
"tail sheds glitter when happy",
"hair becomes fluffy in the rain",
"can speak to flowers",
"has naturally cold hands",
"has naturally warm hands",
"can see hidden doors",
"can smell emotions like scents",
"voice changes with emotions",
"can create tiny shooting stars",
"naturally repels bugs",
"eyes glow during thunderstorms",
"can taste memories in tea",
"always smells like cinnamon",
"leaves snowflakes on mirrors",
"can create floating ribbons",
"can hear stars singing",
"tail wraps around friends protectively",
"creates tiny hearts while sleeping",
"hair becomes longer during winter",
"can summon moonflowers",
"glows softly when reading",
"never burns baked goods",
"can understand ghosts",
"can make stuffed animals move slightly",
"naturally attracts birds",
"can summon cozy sweaters",
"ears flop when sad",
"eyes resemble gemstones",
"creates tiny music notes when humming",
"can calm storms",
"always finds four-leaf clovers",
"can float a few inches when sleepy",
"always smells like strawberries",
"hair shines like silk",
"wings glow with emotions",
"can summon pillows",
"voice can soothe nightmares",
"naturally attracts good dreams",
"tail forms a question mark when curious",
"can summon tiny moons",
"laugh causes flowers to bloom",
"has tiny horns hidden in hair",
"eyes resemble stars in water",
"can create tiny marshmallows",
"always has perfect hair",
"can summon little clouds",
"shadow wags like a tail",
"hair glows at sunset",
"can see wishes being made",
"tail acts on its own",
"can understand old lullabies",
"always smells like hot chocolate",
"can create floating candles",
"wings become transparent in sunlight",
"eyes shimmer like opals",
"can see dream fragments",
"creates tiny butterflies when sneezing",
"has naturally rosy cheeks",
"can summon tea sets",
"voice sounds sweeter when singing",
"can hear moonlight",
"hair changes with phases of the moon",
"can summon tiny rabbits",
"leaves glowing footprints in snow",
"tail rings like a bell",
"can turn hugs into warmth",
"can weave dreams into blankets",
"can create tiny stars in drinks",
"naturally glows near loved ones",
"freckles twinkle when laughing",
"eyes become brighter when curious",
"can make rain smell sweeter",
"can tell fortunes through tea leaves",
"can summon star-shaped cookies",
"tail resembles whipped cream",
"wings look like flower petals",
"hair floats underwater",
"always smells faintly like coffee",
"can create tiny shooting hearts",
"can hear flowers growing",
"naturally attracts moon moths",
"voice echoes in dreams",
"can create floating books",
"can speak to candles",
"hair grows flowers when happy",
"eyes become pastel during spring",
"tail leaves sparkles on blankets",
"can create tiny suns",
"naturally attracts plushies",
"can sense forgotten memories",
"wings fold into a cape",
"can create tiny galaxies in bubbles",
"always knows when someone needs a hug",
"can summon sleepy clouds",
"hair glows during rainstorms",
"eyes shine like stained glass",
"creates tiny stars while baking",
"tail forms little hearts when cuddling",
"can make tea from moonlight",
"naturally smells like fresh bread",
"can create soft lullabies with magic",
"voice makes flowers sway",
"can store memories inside stars",
"freckles resemble tiny flowers",
"can create miniature auroras",
"eyes sparkle when telling stories",
"always leaves warmth behind",
"can see emotions as colors",
"tail becomes fluffy in winter",
"can summon tiny guardian wisps",
"radiates a calming aura"
  ],

  storyHooks: [
"Runs a tiny late-night dessert stall for magical creatures.",
"Inherited a mysterious cafe that only appears during rainstorms.",
"Collects lost wishes and turns them into tiny charms.",
"Designs outfits for spirits who want to visit the human world.",
"Keeps finding magical plushies abandoned on their doorstep.",
"Works at a bookstore where the books whisper secrets after midnight.",
"Is trying to save enough money to open a cozy tea shop.",
"Accidentally became the guardian of a sleepy little star sprite.",
"Makes enchanted sweets that reveal a person's happiest memory.",
"Travels between towns selling charms, snacks, and gentle advice.",

"Maintains a greenhouse where moonflowers only bloom for lonely hearts.",
"Delivers tea to ghosts who cannot leave their old homes.",
"Runs a flower cart with a mischievous fairy companion.",
"Can hear forgotten lullabies hidden inside old music boxes.",
"Works the night shift at a bakery frequented by dream spirits.",
"Repairs damaged plushies that secretly hold memories.",
"Searches antique shops for pieces of a missing constellation.",
"Paints portraits that occasionally come to life while nobody is watching.",
"Hosts weekly tea parties for shy forest spirits.",
"Owns a cat cafe where the cats are disguised familiars.",

"Receives letters addressed to people who haven't been born yet.",
"Helps stars find new places in the night sky.",
"Collects broken umbrellas and restores their magic.",
"Works at a moonlit aquarium filled with impossible creatures.",
"Can see the memories attached to lost jewelry.",
"Runs a cozy inn that only appears on foggy nights.",
"Has a pocket watch that stops whenever fate changes.",
"Finds abandoned dream journals in strange places.",
"Raises tiny cloud sheep in secret.",
"Is searching for the owner of a magical necklace.",

"Was gifted a lantern that attracts wandering souls.",
"Runs a bakery with recipes written by ghosts.",
"Delivers forgotten dreams to sleeping children.",
"Studies at a school hidden inside a giant library.",
"Keeps meeting the same mysterious traveler in different towns.",
"Adopted a tiny dragon that refuses to grow up.",
"Helps moon moths return home during the winter.",
"Inherited a doll shop that comes alive at midnight.",
"Works as a florist for weddings between magical beings.",
"Accidentally entered a contract with a sleepy moon spirit.",

"Collects sea glass that contains memories.",
"Protects a hidden shrine beneath the city.",
"Creates candles that reveal forgotten emotions.",
"Runs an arcade where every machine tells fortunes.",
"Finds old postcards from impossible places.",
"Helps lonely ghosts write letters to their loved ones.",
"Owns a train ticket that leads somewhere different every full moon.",
"Can hear wishes spoken to shooting stars.",
"Runs a tiny market stall during lantern festivals.",
"Searches for recipes left behind by their grandmother.",

"Was chosen by a stubborn little constellation spirit.",
"Keeps rescuing magical creatures from alleyways.",
"Owns a journal that writes back.",
"Works as a tailor for fairies and witches.",
"Can step into paintings while dreaming.",
"Is saving abandoned books from disappearing forever.",
"Delivers enchanted desserts on a bicycle.",
"Accidentally opened a portal inside their closet.",
"Can communicate with old stuffed animals.",
"Runs a bakery famous among moon rabbits.",

"Protects a garden hidden between seasons.",
"Collects tears that turn into crystals.",
"Finds mysterious gifts left on their windowsill.",
"Works at a tiny observatory on a mountain.",
"Can bake memories into cookies.",
"Is trying to reunite a family of lost spirits.",
"Owns a cafe visited by travelers from dreams.",
"Discovers tiny stars hiding inside old toys.",
"Can hear flowers gossiping with each other.",
"Maintains a lighthouse for wandering souls.",

"Was given the job of naming newborn stars.",
"Runs a secondhand shop filled with enchanted trinkets.",
"Searches for a mythical tea recipe.",
"Can see invisible doorways on rainy days.",
"Works as a guide for spirits visiting festivals.",
"Finds tiny notes hidden inside library books.",
"Accidentally befriended a shy ghost prince.",
"Owns a record player that plays forgotten songs.",
"Helps children recover lost dreams.",
"Protects a family recipe book with strange powers.",

"Can speak with creatures hiding in the clouds.",
"Runs a blanket shop loved by sleepy spirits.",
"Discovers magical messages in fortune cookies.",
"Is trying to restore an abandoned greenhouse.",
"Owns a collection of living postcards.",
"Travels with a wagon full of sweets and stories.",
"Finds stars that have fallen to Earth.",
"Works as a caretaker for tiny celestial creatures.",
"Can turn wishes into embroidery patterns.",
"Maintains a hidden moonflower garden for the royal family.",

"Has been tasked with delivering letters to forgotten gods.",
"Can hear stories hidden in seashells.",
"Runs a cozy inn for wandering witches.",
"Searches for the creator of a mysterious plush rabbit.",
"Finds magical recipe cards in random places.",
"Owns a tiny apartment shared with several spirits.",
"Can calm nightmares with handmade tea blends.",
"Travels the countryside restoring abandoned shrines.",
"Was entrusted with a key that opens impossible places.",
"Dreams of opening the warmest little cafe in the world."
  ]
};


const POKEMON_DATA = {
  nameStarts: [
    "Pika", "Eevee", "Mimi", "Luma", "Mochi", "Zappy", "Aqua", "Flora",
    "Cinna", "Nova", "Pebble", "Frosti", "Ember", "Bunni", "Cloud", "Spark",
    "Rosie", "Taffy", "Neko", "Star", "Moon", "Berry", "Choco", "Melo"
  ],

  nameEnds: [
    "chu", "vee", "mon", "puff", "tail", "paw", "whisk", "sprout",
    "spark", "bloom", "beam", "drift", "bun", "fang", "bell", "mew",
    "dash", "drop", "flare", "leaf", "song", "heart", "glow", "nibble"
  ],

  inspirations: [
   // Starters
  "Bulbasaur", "Charmander", "Squirtle", "Chikorita", "Cyndaquil", "Totodile",
  "Treecko", "Torchic", "Mudkip", "Turtwig", "Chimchar", "Piplup",
  "Snivy", "Tepig", "Oshawott", "Chespin", "Fennekin", "Froakie",
  "Rowlet", "Litten", "Popplio", "Grookey", "Scorbunny", "Sobble",
  "Sprigatito", "Fuecoco", "Quaxly",

  // Eeveelutions
  "Eevee", "Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon",
  "Leafeon", "Glaceon", "Sylveon",

  // Cute & Mascot Pokémon
  "Pikachu", "Raichu", "Pichu", "Clefairy", "Clefable", "Jigglypuff",
  "Wigglytuff", "Togepi", "Togetic", "Togekiss", "Marill", "Azumarill",
  "Plusle", "Minun", "Pachirisu", "Emolga", "Dedenne", "Morpeko",
  "Mimikyu", "Chansey", "Blissey", "Audino", "Skitty", "Delcatty",
  "Minccino", "Cinccino", "Buneary", "Lopunny", "Furret", "Sentret",
  "Teddiursa", "Ursaring", "Stufful", "Bewear", "Spheal", "Snom",
  "Wooloo", "Swablu", "Altaria", "Fidough", "Dachsbun", "Milcery",
  "Alcremie", "Cutiefly", "Ribombee", "Comfey", "Whimsicott",

  // Foxes & Canines
  "Vulpix", "Ninetales", "Zorua", "Zoroark", "Rockruff", "Lycanroc",
  "Growlithe", "Arcanine", "Houndour", "Houndoom", "Yamper", "Boltund",
  "Nickit", "Thievul", "Fennekin", "Braixen", "Delphox",

  // Felines
  "Meowth", "Persian", "Glameow", "Purugly", "Litten", "Torracat",
  "Incineroar", "Shinx", "Luxio", "Luxray", "Skitty", "Delcatty",
  "Sprigatito", "Floragato", "Meowscarada", "Espurr", "Meowstic",

  // Bears & Pandas
  "Pancham", "Pangoro", "Cubchoo", "Beartic", "Teddiursa", "Stufful",
  "Bewear", "Kubfu", "Urshifu",

  // Rabbits
  "Buneary", "Lopunny", "Scorbunny", "Raboot", "Cinderace", "Azumarill",

  // Dragons
  "Dratini", "Dragonair", "Dragonite", "Altaria", "Flygon",
  "Goomy", "Sliggoo", "Goodra", "Noibat", "Noivern",
  "Axew", "Fraxure", "Haxorus", "Jangmo-o", "Hakamo-o", "Kommo-o",
  "Cyclizar", "Dragonite", "Hydreigon",

  // Aquatic
  "Lapras", "Primarina", "Vaporeon", "Milotic", "Clauncher",
  "Clawitzer", "Finizen", "Palafin", "Totodile", "Feraligatr",

  // Birds
  "Rowlet", "Dartrix", "Decidueye", "Piplup", "Empoleon",
  "Torchic", "Blaziken", "Oricorio", "Swablu", "Altaria",

  // Anthro Favorites
  "Lucario", "Zeraora", "Gardevoir", "Gallade", "Delphox",
  "Braixen", "Lopunny", "Meowscarada", "Cinderace", "Inteleon",
  "Blaziken", "Tsareena", "Hatterene", "Primarina", "Tinkaton",
  "Mienshao", "Zoroark", "Noivern", "Luxray", "Absol",

  // Soft & Elegant
  "Roserade", "Florges", "Lilligant", "Bellossom", "Leafeon",
  "Glaceon", "Sylveon", "Altaria", "Milotic", "Primarina",
  "Hatterene", "Gardevoir", "Whimsicott", "Comfey",

  // Spooky
  "Mimikyu", "Banette", "Shuppet", "Greavard", "Houndstone",
  "Pumpkaboo", "Gourgeist", "Misdreavus", "Mismagius",
  "Chandelure", "Litwick", "Lampent",

  // Food Pokémon
  "Alcremie", "Appletun", "Dipplin", "Hydrapple", "Vanillite",
  "Vanillish", "Vanilluxe", "Sinistea", "Polteageist",
  "Fidough", "Dachsbun", "Milcery", "Slurpuff", "Swirlix",

  // Fairy
  "Clefable", "Togekiss", "Sylveon", "Ribombee", "Florges",
  "Mawile", "Whimsicott", "Comfey", "Tinkaton", "Hatterene",

  // Legendary/Mythical Favorites
  "Mew", "Celebi", "Jirachi", "Shaymin", "Victini", "Keldeo",
  "Meloetta", "Diancie", "Magearna", "Zeraora",
  "Lunala", "Solgaleo", "Zacian", "Suicune", "Latias",
  "Latios", "Reshiram", "Kyurem", "Miraidon", "Koraidon",

  // Paradox
  "Flutter Mane", "Iron Valiant", "Roaring Moon",
  "Iron Bundle", "Scream Tail", "Great Tusk",

  // Misc Favorites
  "Absol", "Ampharos", "Espeon", "Umbreon", "Noivern",
  "Luxray", "Rapidash", "Ninetales", "Raichu", "Dragonite",
  "Corviknight", "Mudsdale", "Tsareena", "Ceruledge", "Armarouge",
  "Tinkaton", "Clodsire", "Grafaiai", "Pawmot", "Ogerpon"
  ],

  types: [
    "Normal", "Fire", "Water", "Grass", "Electric", "Ice", "Fighting",
    "Poison", "Ground", "Flying", "Psychic", "Bug", "Rock", "Ghost",
    "Dragon", "Dark", "Steel", "Fairy"
  ],

  regionVibes: [
    "Cozy cafe town", "Moonlit forest route", "Snowy mountain village",
    "Pastel city gym district", "Rainy seaside boardwalk", "Cherry blossom shrine",
    "Starry desert observatory", "Cottagecore farming route", "Gothic castle town",
    "Lantern festival village", "Crystal cave region", "Cloudy sky island"
  ],

  habitats: [
    "Sleeps in warm bakery windows", "Lives near glowing moonflowers",
    "Hides inside abandoned plush toys", "Nests near electric streetlamps",
    "Follows travelers through rainy routes", "Guards tiny berry gardens",
    "Lives around cozy cafes", "Appears near music halls at night",
    "Collects shiny stones in caves", "Floats around observatories",
    "Lives in snowy forests", "Plays near flower fields"
  ],

  palettes: [
 "Dusty pink, cream, espresso brown",
"Lavender, black, silver",
"Baby blue, cloud white, soft gold",
"Chocolate brown, rose pink, vanilla",
"Mint, peach, warm cream",
"Deep purple, magenta, moonlight silver",
"Pastel rainbow, white, candy pink",
"Forest green, honey yellow, warm brown",
"Sky blue, lavender, pearl white",
"Sage green, cream, dusty rose",
"Strawberry pink, milk white, cocoa brown",
"Moonlight blue, silver, midnight navy",
"Peach, coral, warm ivory",
"Mint green, white, pale yellow",
"Soft lilac, blush pink, cream",
"Black, crimson, silver",
"Plum purple, charcoal, lavender",
"Rose gold, ivory, champagne",
"Sunflower yellow, sage green, cream",
"Ocean blue, seafoam, sandy beige",
"Teal, peach, white",
"Sky blue, lemon yellow, white",
"Ruby red, black, gold",
"Emerald green, cream, copper",
"Periwinkle, pink, white",
"Coffee brown, caramel, cream",
"Soft orange, honey, vanilla",
"Lavender, mint, baby pink",
"Cotton candy pink, aqua, white",
"Storm gray, silver, icy blue",
"Wine red, blush pink, black",
"Pastel yellow, mint, lavender",
"Powder blue, silver, white",
"Coral pink, cream, mocha",
"Midnight blue, violet, silver",
"Sakura pink, white, pale green",
"Chocolate, cream, strawberry pink",
"Berry purple, blush, cream",
"Rose red, black, ivory",
"Honey gold, cream, cinnamon",
"Seafoam green, sky blue, white",
"Lilac, silver, moon white",
"Baby pink, lavender, mint",
"Peach cream, cocoa, rose pink",
"Sunset orange, coral, cream",
"Indigo, silver, pale lavender",
"Forest green, cream, amber",
"Blueberry blue, cream, lilac",
"Warm beige, caramel, espresso",
"Cloud gray, baby blue, white",
"Rose pink, mauve, cream",
"Mint green, cocoa brown, vanilla",
"Silver, navy, moon blue",
"Soft red, cream, dusty pink",
"Pumpkin orange, sage green, cream",
"Black, purple, rose gold",
"Golden yellow, white, honey brown",
"Sky blue, mint, cream",
"Bubblegum pink, white, pale blue",
"Maroon, black, gold",
"Teal, navy, silver",
"Strawberry pink, cream, mint",
"Mocha brown, dusty rose, ivory",
"Peach, lavender, white",
"Pastel blue, lemon, pink",
"Dark green, copper, beige",
"Coral, aqua, white",
"Periwinkle, cream, pale gold",
"Rose pink, pearl white, silver",
"Chocolate brown, vanilla, caramel",
"Black, crimson, moon silver",
"Sage green, peach, cream",
"Blue gray, silver, white",
"Deep teal, pale gold, ivory",
"Plum purple, pink, cream",
"Cherry red, black, white",
"Cloud white, baby pink, lavender",
"Honey yellow, cream, soft orange",
"Emerald green, gold, black",
"Peach pink, warm white, cocoa",
"Sky blue, moon silver, navy",
"Mint green, white, pastel pink",
"Lilac purple, cream, silver",
"Rosewood, blush pink, ivory",
"Caramel, cream, honey gold",
"Blueberry, lavender, cream",
"Black, silver, wine red",
"Sea blue, white, coral",
"Pastel mint, peach, white",
"Strawberry red, cream, chocolate",
"Moon blue, lavender, silver",
"Sage green, ivory, mocha",
"Cloud white, pale yellow, blue",
"Magenta, deep purple, silver",
"Rose gold, blush, cream",
"Sky blue, lilac, white",
"Espresso brown, cream, soft pink",
"Sunflower yellow, peach, cream",
"Periwinkle, pink, mint",
"Charcoal gray, lavender, silver",
"Coral pink, white, gold",
"Baby blue, silver, lavender",
"Cinnamon brown, cream, blush",
"Forest green, beige, amber",
"Mint, ivory, pale gold",
"Chocolate brown, cherry red, cream",
"Rose pink, white, soft gray",
"Moonlight silver, navy, pale blue",
"Strawberry milk pink, cream, cocoa",
"Lemon yellow, white, mint",
"Royal purple, black, silver",
"Soft aqua, white, pearl",
"Honey gold, mocha, cream",
"Blush pink, sage green, ivory",
"Blue lavender, white, silver",
"Rose red, cream, champagne",
"Midnight navy, silver, lavender",
"Peach, strawberry pink, vanilla",
"Soft green, cream, honey",
"Baby pink, white, pale yellow",
"Berry purple, moon silver, black",
"Cloud blue, cream, lavender",
"Mint, blush pink, white",
"Copper, cream, espresso",
"Coral orange, pale yellow, white",
"Periwinkle blue, pearl, pink",
"Rosewood red, gold, cream",
"Sky blue, cloud gray, white",
"Chocolate brown, vanilla cream, pink",
"Lavender, moon blue, silver",
"Forest moss, honey, cream",
"Candy pink, pastel blue, white",
"Teal green, cream, peach",
"Midnight purple, silver, black",
"Peach cream, dusty rose, ivory",
"Baby blue, mint, white",
"Warm caramel, cream, coffee brown",
"Rose quartz pink, silver, white",
"Seafoam green, ivory, pale blue",
"Crimson, black, silver",
"Plum, blush pink, cream",
"Honey yellow, sage, beige",
"Pastel rainbow, pearl white, lavender",
"Soft coral, vanilla, cocoa",
"Moonlight blue, cloud white, silver",
"Espresso brown, cream, caramel",
"Sakura pink, pearl, mint",
"Storm gray, navy, silver",
"Mint green, pale peach, ivory",
"Rose pink, chocolate brown, cream",
"Sunset peach, lavender, white",
"Berry blue, silver, white",
"Warm cream, honey gold, brown",
"Black, plum, rose gold",
"Sky blue, pale lavender, pearl",
"Forest green, cream, cinnamon",
"Blueberry purple, pink, white",
"Vanilla cream, blush, caramel",
"Deep navy, moon silver, white",
"Peach pink, mint green, cream",
"Cherry blossom pink, white, gold",
"Teal blue, silver, ivory",
"Soft yellow, cream, peach",
"Rose red, black, moon silver",
"Baby blue, cotton pink, white",
"Sage green, dusty rose, cream",
"Chocolate brown, strawberry pink, vanilla",
"Lavender gray, silver, white",
"Sunflower yellow, honey brown, cream",
"Mint blue, white, silver",
"Pastel peach, lilac, cream",
"Forest green, amber, ivory",
"Deep purple, pink, silver",
"Pearl white, blush pink, champagne",
"Caramel brown, cream, rose",
"Sky blue, moon white, pale gold",
"Seafoam, mint, ivory",
"Black, magenta, silver",
"Berry pink, cream, mocha",
"Cloud white, baby blue, lavender",
"Honey gold, cream, sage green",
"Rosewood, blush, moon silver",
"Bluebell blue, white, pink",
"Espresso brown, vanilla, honey",
"Peach, coral pink, ivory",
"Midnight blue, lavender, moon silver"
  ],

  personalities: [
  "soft-spoken", "dramatic", "bratty", "motherly", "mischievous",
"sleepy", "spoiled", "loyal", "chaotic", "gentle", "protective",
"curious", "flirty", "bookish", "clumsy", "confident",
"shy", "timid", "bashful", "playful", "cheerful", "optimistic",
"pessimistic", "sarcastic", "witty", "goofy", "energetic", "hyper",
"laid-back", "easygoing", "reserved", "quiet", "talkative", "bubbly",
"affectionate", "clingy", "attention-seeking", "stubborn", "determined",
"independent", "dependable", "caring", "nurturing", "patient",
"impatient", "romantic", "dreamy", "creative", "artistic", "musical",
"organized", "messy", "scatterbrained", "forgetful", "responsible",
"mature", "childish", "whimsical", "eccentric", "elegant", "graceful",
"awkward", "anxious", "worry-prone", "sensitive", "empathetic",
"compassionate", "kind-hearted", "selfless", "selfish", "vain",
"vain-but-sweet", "fashionable", "stylish", "trendy", "old-fashioned",
"traditional", "rebellious", "free-spirited", "adventurous",
"cautious", "carefree", "reckless", "bold", "fearless", "cowardly",
"competitive", "cooperative", "helpful", "supportive", "observant",
"analytical", "logical", "emotional", "passionate", "fiery",
"hot-headed", "calm", "collected", "stoic", "mysterious",
"secretive", "honest", "blunt", "polite", "well-mannered",
"sassy", "snarky", "teasing", "friendly", "welcoming",
"charismatic", "charming", "sweet", "innocent", "naive",
"street-smart", "clever", "resourceful", "hardworking", "lazy",
"sleep-loving", "foodie", "tea-loving", "coffee-obsessed",
"workaholic", "perfectionist", "ambitious", "content", "humble",
"prideful", "grumpy", "tsundere", "kuudere", "yandere",
"deredere", "airheaded", "ditzy", "gullible", "trusting",
"suspicious", "guarded", "protective-big-sibling", "mother-hen",
"big-hearted", "gentle giant", "tiny menace", "gremlin",
"chaos goblin", "prankster", "joker", "class clown",
"daydreamer", "starry-eyed", "hopeful", "sentimental", "nostalgic",
"melancholic", "brooding", "gothic", "spooky", "witchy",
"nature-loving", "animal-loving", "bookworm", "scholarly",
"intellectual", "nerdy", "tech-savvy", "crafty", "resourceful",
"perceptive", "intuitive", "wise", "motherly-but-strict",
"gentle-but-firm", "soft-hearted", "forgiving", "vengeful",
"jealous", "possessive", "devoted", "faithful", "protective-big-brother",
"protective-big-sister", "clingy-but-caring", "shameless",
"dramatic-princess", "spoiled-princess", "cozy", "homebody",
"social butterfly", "introverted", "extroverted", "ambiverted",
"adorkable", "excitable", "curiosity-driven", "peaceful",
"serene", "radiant", "sunny", "moonlike", "starry-eyed",
"softie", "cinnamon-roll", "crybaby", "resilient", "tenacious",
"headstrong", "gentle soul", "warm-hearted", "lovable menace",
"unapologetically herself", "surprisingly nurturing"
  ],

  trainerRoles: [
    "Cafe companion Pokemon", "Contest partner", "Gym leader ace",
    "Cozy route friend", "Traveling partner", "Pokemon Center helper",
    "Mystery dungeon guide", "Ranger partner", "Festival mascot",
    "Bakery delivery helper", "Night patrol companion", "Starter Pokemon candidate"
  ],

  abilities: [
  "Comfort Aura", "Moonlit Veil", "Sugar Rush", "Static Charm",
  "Cozy Guard", "Dream Glow", "Berry Finder", "Soft Paws",
  "Star Shield", "Sweet Scent", "Lucky Spark", "Gentle Heart",
  "Cloud Drift", "Frost Fluff", "Ember Bloom", "Ribbon Guard",

  "Lunar Blessing", "Sunny Spirit", "Cuddle Shield", "Dream Walker",
  "Honey Heart", "Starlight Pulse", "Mystic Whiskers", "Velvet Breeze",
  "Moonbeam Tail", "Sparkling Fur", "Comfy Nap", "Pastel Power",
  "Twinkle Veil", "Aurora Coat", "Tea Time", "Wish Keeper",
  "Bubble Charm", "Petal Dance", "Cloud Cushion", "Rosy Glow",
  "Gentle Breeze", "Nightlight", "Warm Hug", "Lucky Clover",
  "Moonflower Bloom", "Berry Burst", "Dew Kiss", "Crystal Shine",
  "Rainbow Ribbon", "Snow Puff", "Sunbeam Smile", "Plush Guard",
  "Starry Eyes", "Magic Mittens", "Whispering Wind", "Shimmer Coat",
  "Dream Catcher", "Moonshadow", "Cloud Hopper", "Cozy Nest",
  "Fairy Dust", "Sugar Sprinkle", "Lullaby Song", "Soft Landing",
  "Sunrise Spirit", "Moonrise Blessing", "Wish Upon", "Sky Waltz",
  "Lantern Glow", "Starlit Path", "Tea Aroma", "Cocoa Warmth",
  "Buttercream Body", "Candy Spark", "Velvet Touch", "Petal Veil",
  "Rose Charm", "Sleepy Yawn", "Kind Soul", "Healing Hum",
  "Cloudy Day", "Snow Blanket", "Starfall", "Lunar Halo",
  "Magic Thread", "Plush Parade", "Comet Tail", "Ribbon Dance",
  "Marshmallow Coat", "Sunny Disposition", "Rainy Melody", "Dream Drift",
  "Moonlit Grace", "Sweet Dream", "Snuggle Time", "Morning Dew",
  "Twilight Glow", "Sparkle Trail", "Honey Coat", "Warm Cookies",
  "Tea Leaves", "Cosmic Cuddle", "Bubble Wrap", "Velvet Nap",
  "Dream Fluff", "Gentle Breeze", "Sunflower Smile", "Rain Dance",
  "Lucky Paws", "Daisy Chain", "Moon Petals", "Frost Bloom",
  "Cloud Cover", "Night Song", "Sweet Kiss", "Berry Basket",
  "Wish Ribbon", "Moonlight Waltz", "Golden Heart", "Spirit Hug",
  "Comfy Blanket", "Sleep Walker", "Rainbow Trail", "Shiny Paws",
  "Tea Party", "Star Dust", "Warm Wishes", "Misty Fur",
  "Flower Shower", "Dream Weaver", "Magic Beans", "Honey Glow",
  "Petal Storm", "Moon Echo", "Lunar Luck", "Fairy Waltz",
  "Plushie Bond", "Stargazer", "Bubble Coat", "Candy Cloud",
  "Sunset Glow", "Midnight Whisper", "Twinkle Tail", "Cozy Spark",
  "Cloud Nine", "Gentle Melody", "Moonbeam Hug", "Dream Song",
  "Sleepy Aura", "Kindred Spirit", "Dewdrop Blessing", "Star Gleam",
  "Mystic Ribbon", "Cuddle Pulse", "Moonveil", "Sunflare Soul",
  "Snowy Snuggle", "Cotton Puff", "Fairy Breeze", "Warm Embrace",
  "Berry Patch", "Moon Garden", "Sky Blessing", "Aurora Veil",
  "Magic Muffin", "Cloud Waltz", "Crystal Fur", "Sweet Harmony",
  "Wish Bloom", "Dawn Glow", "Twilight Aura", "Lunar Lullaby",
  "Cozy Vibes", "Ribbon Charm", "Dream Dust", "Cloud Song",
  "Moonlit Purr", "Tea Steam", "Cookie Crumbs", "Sparkle Coat",
  "Flower Crown", "Dream Bubble", "Comet Wish", "Sugar Coat",
  "Sunny Hug", "Moonlit Eyes", "Starlight Kiss", "Warm Soul",
  "Rainbow Mist", "Bubble Trail", "Velvet Fur", "Petal Whisper",
  "Cloudy Dreams", "Starry Nap", "Wishful Heart", "Honey Dew",
  "Moon Petal", "Lullaby Aura", "Twinkle Song", "Magic Paw",
  "Dream Halo", "Gentle Glow", "Sunbeam Blessing", "Comet Drift",
  "Plush Heart", "Star Garden", "Moonlit Comfort", "Sweet Spirit",
  "Aurora Dream", "Cloud Blessing", "Moon Bunny", "Lucky Charm",
  "Frosted Heart", "Candy Veil", "Celestial Bond", "Dreamy Soul"
],

  moveStyles: [
  "Uses heart-shaped sparkles to distract opponents.",
  "Attacks with glowing ribbons and moonlight beams.",
  "Curls into a ball and rolls like a fluffy meteor.",
  "Summons tiny stars that burst like fireworks.",
  "Uses soft singing moves to calm wild Pokemon.",
  "Throws enchanted berries that explode into glitter.",
  "Creates cozy mist that lowers enemy accuracy.",
  "Charges with oversized paws and surprising speed.",
  "Uses dessert-themed attacks with sticky frosting.",
  "Creates a protective bubble of warm light.",

  "Whips enemies with glowing flower vines.",
  "Creates tiny clouds that rain sparkling droplets.",
  "Fires crescent moons like boomerangs.",
  "Summons butterflies that scatter magical pollen.",
  "Uses playful spins to confuse opponents.",
  "Creates a shield of floating plushies.",
  "Launches star-shaped cookies with surprising force.",
  "Throws glowing tea leaves that drain energy.",
  "Uses a warm hug to heal allies.",
  "Spins ribbons around enemies to bind them.",

  "Creates an aurora that boosts allies' morale.",
  "Summons sleepy clouds that make foes drowsy.",
  "Fires bubbles filled with glittering light.",
  "Attacks with paws coated in frost.",
  "Creates candy explosions that stick to opponents.",
  "Throws moonflower petals like shurikens.",
  "Uses a cheerful dance to increase speed.",
  "Unleashes tiny comets from its tail.",
  "Creates a field of soft grass that restores health.",
  "Calls down beams of moonlight from above.",

  "Uses spinning kicks wrapped in ribbons.",
  "Creates floating stars that orbit before exploding.",
  "Attacks with sweet-scented gusts of wind.",
  "Summons plush bunnies to tackle opponents.",
  "Charges with sparkling antlers.",
  "Creates mirrors of itself using dream magic.",
  "Launches glowing feathers like darts.",
  "Summons a wave of warm cocoa.",
  "Uses sleepy yawns to weaken enemies.",
  "Creates flower crowns that absorb damage.",

  "Rolls through enemies while surrounded by rainbow light.",
  "Creates tiny lantern wisps that chase opponents.",
  "Uses musical notes as projectiles.",
  "Forms crystal flowers that burst into shards.",
  "Creates bubbles that explode into hearts.",
  "Swings oversized paws with surprising grace.",
  "Uses magical embroidery threads to bind foes.",
  "Fires marshmallow puffs that slow enemies.",
  "Summons moon moths to distract targets.",
  "Uses tea steam to obscure the battlefield.",

  "Creates a blanket of snow that protects allies.",
  "Throws glowing acorns like bombs.",
  "Calls down tiny meteors from the sky.",
  "Attacks with a swirling galaxy around its body.",
  "Uses a soft purr to restore energy.",
  "Creates dream portals beneath enemies.",
  "Unleashes waves of pastel flames.",
  "Summons floating books to strike opponents.",
  "Creates clouds that absorb incoming attacks.",
  "Uses star-shaped punches with dazzling effects.",

  "Forms shields out of moon petals.",
  "Attacks with glitter-coated claws.",
  "Creates tiny suns that orbit the battlefield.",
  "Uses spinning twirls to evade attacks.",
  "Summons ghostly plushies that protect allies.",
  "Throws enchanted candies that split into smaller projectiles.",
  "Creates soothing rain that heals teammates.",
  "Uses glowing paws to deliver rapid strikes.",
  "Calls spirits hidden inside lanterns.",
  "Creates flower storms that slow enemies.",

  "Launches crystal stars in all directions.",
  "Creates rainbow bubbles that burst into mist.",
  "Uses magical lullabies to reduce aggression.",
  "Attacks with crescent-shaped wind blades.",
  "Creates giant pillows that cushion allies.",
  "Summons dancing lights that confuse foes.",
  "Uses fluffy tail swipes that leave sparkles.",
  "Calls down sunbeams wrapped in ribbons.",
  "Creates dream mist that hides allies.",
  "Uses gentle headbutts infused with moonlight.",

  "Throws tea cups filled with magical energy.",
  "Creates a blizzard of flower petals.",
  "Uses twinkling eyes to stun opponents.",
  "Summons stars that bounce around unpredictably.",
  "Creates candy canes that strike from below.",
  "Uses glowing wings to create shockwaves.",
  "Forms giant hearts that absorb attacks.",
  "Creates sweet aromas that weaken foes.",
  "Unleashes a wave of pastel lightning.",
  "Attacks while spinning like a ballerina.",

  "Summons tiny dragons made of clouds.",
  "Uses a ribbon whip enhanced with fairy magic.",
  "Creates snowflakes that explode into light.",
  "Calls down sparkling rainbows from above.",
  "Uses sleepy cuddles to sap enemy strength.",
  "Creates moonlit puddles that slow movement.",
  "Launches glowing berries with pinpoint accuracy.",
  "Uses fluffy ears like fans to create gusts.",
  "Creates constellations that rain stars.",
  "Attacks with floating crystal roses.",

  "Creates a blanket fort barrier around allies.",
  "Uses tiny bells to unleash sound waves.",
  "Summons dream sheep that charge opponents.",
  "Creates shimmering lace traps.",
  "Uses a warm lantern to repel darkness.",
  "Throws moon-shaped charms that explode.",
  "Creates magical tea steam that burns lightly.",
  "Uses clouds as stepping stones for aerial attacks.",
  "Forms giant bows that strike like whips.",
  "Summons tiny guardian spirits to assist in battle.",

  "Creates a galaxy around itself and crashes like a comet.",
  "Uses star-shaped punches that leave glitter trails.",
  "Calls down moonbeams that heal allies and harm enemies.",
  "Creates flower vines that gently bind opponents.",
  "Uses plush toys as magical missiles.",
  "Summons warm sunlight that restores stamina.",
  "Attacks with sparkling raindrops that multiply.",
  "Uses dream bubbles that pop into bursts of light.",
  "Creates a soft aura that reflects status effects.",
  "Unleashes a dazzling explosion of stars, ribbons, and moonlight."
],

  heldItems: [
  "Soothe Bell", "Moon Stone Charm", "Ribbon Scarf", "Berry Basket",
  "Tiny Bell Collar", "Star-Shaped Cookie", "Warm Cafe Mug",
  "Mystic Ribbon", "Glittery Shell", "Friendship Bracelet",
  "Soft Blanket Scrap", "Lucky Charm",

  "Moonflower Pendant", "Tiny Plush Keychain", "Honey Jar",
  "Crystal Acorn", "Star Cookie Tin", "Tea Leaf Sachet",
  "Dreamcatcher Charm", "Mini Spellbook", "Lucky Penny",
  "Warm Muffin", "Flower Crown", "Sunflower Pin",
  "Moon Pendant", "Star Pendant", "Cloud Charm",
  "Tiny Lantern", "Ribbon Bow", "Pearl Bracelet",
  "Rose Quartz", "Heart Locket", "Crochet Pouch",
  "Pocket Notebook", "Bookmark Tassel", "Tiny Umbrella",
  "Magic Teaspoon", "Mini Jam Jar", "Sugar Cube",
  "Sleep Mask", "Paw Print Collar", "Comfy Scarf",
  "Knitted Mittens", "Lace Handkerchief", "Tea Cup Charm",
  "Moonphase Bracelet", "Sun Charm", "Constellation Brooch",
  "Velvet Ribbon", "Tiny Music Box", "Crystal Bell",
  "Strawberry Hair Clip", "Star Hair Pin", "Flower Anklet",
  "Lucky Dice", "Rainbow Marble", "Polished Sea Glass",
  "Shell Necklace", "Mini Treasure Chest", "Golden Feather",
  "Cloud Plush", "Moon Plush", "Star Plush",
  "Bunny Plush", "Bear Plush", "Fox Plush",
  "Tiny Pillow", "Warm Cookie", "Chocolate Bar",
  "Berry Tart", "Macaron Box", "Cupcake Charm",
  "Candy Cane", "Marshmallow Puff", "Boba Cup",
  "Coffee Bean Pouch", "Hot Cocoa Mix", "Honey Cookie",
  "Blueberry Muffin", "Moon Cake", "Taiyaki Charm",
  "Dango Skewer", "Ice Cream Scoop Charm", "Tiny Whisk",
  "Apron Pocket", "Recipe Card", "Rolling Pin Charm",
  "Magic Spoon", "Pastry Box", "Cinnamon Stick",
  "Lavender Sachet", "Mint Leaf Bundle", "Moonflower Seed",
  "Pressed Rose", "Sunflower Petal", "Four-Leaf Clover",
  "Tiny Watering Can", "Garden Gloves", "Crystal Flower",
  "Butterfly Brooch", "Bee Pin", "Firefly Lantern",
  "Star Map", "Pocket Compass", "Silver Pocket Watch",
  "Tiny Telescope", "Moon Journal", "Dream Diary",
  "Fountain Pen", "Ink Bottle Charm", "Tiny Bookmark",
  "Scrapbook Page", "Photo Locket", "Vintage Postcard",
  "Tiny Camera", "Music Note Charm", "Vinyl Record Pin",
  "Mini Harp", "Bell Earrings", "Moon Earrings",
  "Crystal Earrings", "Heart Earrings", "Star Earrings",
  "Lace Choker", "Rose Choker", "Pearl Choker",
  "Tiny Cape", "Velvet Capelet", "Cozy Cardigan",
  "Wool Socks", "Fluffy Slippers", "Patchwork Quilt Scrap",
  "Dream Pillow", "Moon Blanket", "Star Quilt",
  "Tiny Candle", "Scented Candle", "Moonlight Candle",
  "Vanilla Perfume", "Rose Perfume", "Lavender Perfume",
  "Crystal Vial", "Potion Bottle", "Fairy Dust Jar",
  "Tiny Snow Globe", "Glass Star", "Rainbow Prism",
  "Moonstone Ring", "Opal Ring", "Rose Gold Ring",
  "Silver Ring", "Charm Anklet", "Lucky Coin",
  "Tiny Treasure Map", "Cloud Feather", "Dragon Scale",
  "Phoenix Feather", "Fairy Wing Fragment", "Aurora Crystal",
  "Sun Fragment", "Star Fragment", "Moon Fragment",
  "Wish Token", "Fortune Cookie", "Tiny Envelope",
  "Love Letter", "Sealed Note", "Postage Stamp",
  "Mini Lantern", "Paper Crane", "Origami Star",
  "Tiny Book of Poems", "Storybook", "Comic Book",
  "Board Game Piece", "Dice Bag", "Card Deck",
  "Tiny Hourglass", "Sand Dollar", "Coral Fragment",
  "Pearl Shell", "Seashell Necklace", "Ocean Bottle",
  "Mini Aquarium Charm", "Bubble Wand", "Rainbow Ribbon",
  "Moon Ribbon", "Star Ribbon", "Sun Ribbon",
  "Flower Ribbon", "Pastel Bow", "Golden Bow",
  "Tiny Crown", "Moon Tiara", "Star Tiara",
  "Heart Gem", "Crystal Heart", "Dream Crystal",
  "Wish Crystal", "Snowflake Crystal", "Galaxy Crystal",
  "Aurora Charm", "Cloud Charm Bracelet", "Magic Yarn",
  "Crochet Flower", "Knitting Needle Charm", "Embroidery Hoop",
  "Tiny Plush Backpack", "Mushroom Charm", "Acorn Pendant",
  "Tiny Bat Plush", "Moon Bunny Charm", "Celestial Brooch",
  "Tea Set Charm", "Cozy Lantern", "Starry Mug"
],

  specialTraits: [
  "Its tail glows when it trusts someone.",
  "It purrs when healed at a Pokemon Center.",
  "It leaves paw-shaped sparkles behind.",
  "Its ears twitch when hidden items are nearby.",
  "It changes color slightly under moonlight.",
  "It brings berries to sad trainers.",
  "It sleeps better inside oversized hoodies.",
  "It can sense when its trainer is lonely.",
  "It sings softly before using special moves.",
  "It stores tiny stars in its fur.",

  "Its cheeks glow when excited.",
  "It always smells faintly like vanilla.",
  "It collects shiny pebbles as gifts.",
  "Its fur becomes fluffier in winter.",
  "It hums while falling asleep.",
  "Its eyes resemble tiny galaxies.",
  "It likes sleeping on warm laptops.",
  "Its shadow waves independently when happy.",
  "It leaves flower petals behind when running.",
  "It hides snacks inside its fluffy tail.",

  "Its ears droop when someone nearby is sad.",
  "It creates tiny rainbows when sneezing.",
  "It always finds the warmest spot in the room.",
  "Its fur crackles with static during storms.",
  "It adores being wrapped in blankets.",
  "Its paws glow during full moons.",
  "It attracts butterflies without trying.",
  "It can smell fresh cookies from miles away.",
  "Its whiskers twitch around rare Pokémon.",
  "It loves collecting bottle caps.",

  "It dreams with its eyes slightly open.",
  "It sleeps curled around plushies.",
  "It becomes sleepy during rainy weather.",
  "Its tail forms a heart when happy.",
  "Its cry sounds like tiny bells.",
  "It always shares berries with friends.",
  "Its fur sparkles after baths.",
  "It glows brighter near loved ones.",
  "Its nose wiggles when curious.",
  "It enjoys watching snowfall.",

  "It carries tiny flowers in its fur.",
  "Its ears perk up around music.",
  "It falls asleep during car rides.",
  "Its footsteps leave faint glitter.",
  "It always knows when a storm is coming.",
  "It can recognize its trainer's voice from far away.",
  "Its eyes change shades with its mood.",
  "It naps best while cuddling.",
  "It likes sitting in windowsills.",
  "It can hear distant lullabies.",

  "It chirps quietly while dreaming.",
  "It gets hiccups after eating sweet berries.",
  "It can sense hidden emotions.",
  "Its fur smells like warm bread after naps.",
  "It likes wearing ribbons.",
  "Its tail becomes extra fluffy when relaxed.",
  "It can tell when someone needs a hug.",
  "It tilts its head while listening to stories.",
  "Its cry echoes softly under moonlight.",
  "It enjoys watching stars at night.",

  "It stores shiny things beneath pillows.",
  "It often brings flowers to its trainer.",
  "It enjoys sitting on books while people read.",
  "Its ears glow faintly during sunsets.",
  "It follows fireflies for fun.",
  "It can always find lost socks.",
  "Its fur warms itself when cold.",
  "It wiggles excitedly before battles.",
  "It enjoys rainy afternoons.",
  "It can smell happiness like flowers.",

  "Its paws leave tiny clouds in snow.",
  "It likes hiding beneath oversized sweaters.",
  "It falls asleep during long conversations.",
  "Its fur shines after eating berries.",
  "It enjoys listening to piano music.",
  "It loves collecting ribbons.",
  "Its tail curls around trusted friends.",
  "It likes sitting on warm laundry.",
  "Its eyes sparkle while eating treats.",
  "It stores feathers in secret places.",

  "It gently nudges crying people.",
  "Its whiskers glow in the dark.",
  "It prefers sleeping under blankets.",
  "It loves being carried around.",
  "Its tail acts independently when excited.",
  "It hums happily while eating.",
  "Its fur changes slightly with the seasons.",
  "It loves sitting near fireplaces.",
  "Its ears flop when embarrassed.",
  "It always saves the last berry for someone else.",

  "It can tell when rain is approaching.",
  "Its fur becomes softer after moonrise.",
  "It loves chasing falling leaves.",
  "Its cry becomes sweeter when happy.",
  "It likes sleeping beside books.",
  "Its nose twitches when excited.",
  "It loves cuddling with plush toys.",
  "Its tail glimmers after making friends.",
  "It enjoys warm tea scents.",
  "It often stares at the moon for no reason.",

  "It wraps its tail around injured friends.",
  "Its eyes shine like gemstones in sunlight.",
  "It likes making nests from blankets.",
  "Its fur smells like lavender after grooming.",
  "It dances when it hears cheerful music.",
  "It hides beneath tables during thunderstorms.",
  "Its ears twitch when someone says its name.",
  "It enjoys watching fish swim.",
  "It likes collecting seashells.",
  "Its cry sounds softer around children.",

  "It brings lucky pebbles to its trainer.",
  "It loves sleeping in laundry baskets.",
  "Its tail becomes puffier when proud.",
  "It likes carrying tiny flowers.",
  "Its fur glows after being praised.",
  "It often dozes off while being brushed.",
  "It enjoys cloud-watching.",
  "Its eyes become brighter while playing.",
  "It likes sitting on shoulders.",
  "It often falls asleep while eating treats.",

  "It stores tiny moonbeams in its fur.",
  "It can sense good dreams nearby.",
  "Its paws never make noise indoors.",
  "It creates little sparks when surprised.",
  "Its fur shimmers during full moons.",
  "It prefers sleeping beside trusted friends.",
  "Its ears wiggle while happy.",
  "It likes carrying stuffed toys everywhere.",
  "Its cry resembles a soft lullaby.",
  "It naturally comforts nervous Pokémon.",

  "It gently headbutts people it loves.",
  "Its eyes twinkle like stars at night.",
  "It enjoys cozy corners and window seats.",
  "Its tail glows while dreaming.",
  "It instinctively protects sleeping friends.",
  "It creates tiny bubbles when excited.",
  "Its fur smells faintly like strawberries.",
  "It enjoys falling asleep to stories.",
  "It often gifts trainers shiny leaves.",
  "It radiates a calming warmth wherever it goes."
],

  storyHooks: [
  "A shy trainer finds it hiding behind a cafe during a thunderstorm.",
  "It becomes the mascot of a tiny Pokemon bakery.",
  "It keeps sneaking into contests because it loves applause.",
  "It follows a traveling trainer after being given a warm snack.",
  "It guards a moonflower field where rare Pokemon gather.",
  "It is rumored to appear only during lantern festivals.",
  "A gym leader uses it as their unexpectedly powerful ace.",
  "It helps lost Pokemon find their way home at night.",
  "It was found asleep inside an abandoned plush backpack.",
  "It bonds with trainers who share their lunch.",

  "It secretly lives in the attic of a cozy bookstore.",
  "A florist discovered it sleeping among the roses.",
  "It only appears to people who are feeling lonely.",
  "It accidentally became the star attraction of a local cafe.",
  "It follows musicians and falls asleep during concerts.",
  "A child mistook it for a plush toy and brought it home.",
  "It delivers berries to elderly trainers every morning.",
  "It was rescued from a snowstorm and never left its trainer's side.",
  "Wild Pokemon trust it enough to gather around it.",
  "It sneaks into Pokemon Centers just for head pats.",

  "It was found guarding an abandoned picnic basket.",
  "A librarian caught it sleeping between the pages of books.",
  "It enjoys hiding inside oversized hoodies.",
  "It once wandered into a Contest Hall and became famous overnight.",
  "It follows people who smell like pastries.",
  "It likes napping on top of warm Rotom devices.",
  "It adopted its trainer before they could adopt it.",
  "It was discovered inside a flower shop after a rainstorm.",
  "It helps Nurse Joy comfort nervous Pokemon.",
  "It is beloved by children for its gentle nature.",

  "It likes listening to bedtime stories with younger Pokemon.",
  "It once won a ribbon by accident while looking for snacks.",
  "It helps maintain a hidden moonflower garden.",
  "It often guides lost travelers during foggy nights.",
  "It was discovered in the luggage compartment of a train.",
  "A wandering baker shares leftovers with it every evening.",
  "It became best friends with the local Audino.",
  "It protects abandoned eggs until help arrives.",
  "It only trusts trainers who offer berries politely.",
  "It enjoys sleeping inside laundry baskets.",

  "It follows lantern lights during festivals.",
  "A retired trainer takes care of several of them.",
  "It can often be found sleeping in libraries.",
  "It once interrupted a Gym Battle for attention.",
  "It became famous after helping rescue lost Pokemon.",
  "It prefers sleeping on soft blankets over beds.",
  "It likes accompanying trainers on late-night walks.",
  "It often watches the stars with Clefairy.",
  "It visits the same cafe every morning.",
  "It leaves flowers on the graves of departed Pokemon.",

  "It helps shy Pokemon make friends.",
  "It enjoys performing for children at parks.",
  "It once got stuck in a claw machine and was mistaken for a prize.",
  "It follows musicians through cities and towns.",
  "It loves sleeping under Christmas trees.",
  "It befriended a lonely Ghost-type and never left them.",
  "It became a mascot for a berry farm.",
  "It helps wild Pokemon survive harsh winters.",
  "It enjoys decorating itself with ribbons.",
  "It likes sitting beside campfires.",

  "It was discovered while curled up inside a mailbox.",
  "It likes collecting shiny bottle caps.",
  "It follows trainers who hum songs.",
  "It can be seen watching sunsets from rooftops.",
  "It once wandered into a fashion show and stole the spotlight.",
  "It became attached to a traveling artist.",
  "It enjoys sleeping in flower beds.",
  "It follows people carrying warm tea.",
  "It often helps Chansey deliver supplies.",
  "It is rumored to understand human emotions.",

  "It protects smaller Pokemon from bullies.",
  "It loves attending local festivals.",
  "It frequently naps in greenhouses.",
  "It became famous after appearing on television.",
  "It likes watching snow fall from windows.",
  "It was rescued by a trainer during a storm.",
  "It helps lost children find their parents.",
  "It shares berries with hungry Pokemon.",
  "It enjoys sleeping near fireplaces.",
  "It once won a beauty contest by doing absolutely nothing.",

  "It likes watching trains pass by.",
  "It became friends with a lonely Absol.",
  "It spends nights staring at the moon.",
  "It is believed to bring good dreams.",
  "It helps clean up parks after festivals.",
  "It enjoys listening to old records.",
  "It follows trainers who read books aloud.",
  "It often naps beside Mareep herds.",
  "It became the mascot of a sleepy mountain town.",
  "It likes watching aquariums for hours.",

  "It was discovered asleep in a delivery truck.",
  "It became attached to a baker who fed it cookies.",
  "It likes sleeping beneath potted plants.",
  "It often visits elderly trainers.",
  "It likes watching rain from windowsills.",
  "It is strangely fascinated by plush toys.",
  "It follows people who laugh often.",
  "It shares its warm fur with smaller Pokemon.",
  "It once interrupted an Elite Four meeting to nap.",
  "It became famous after a photo of it sleeping went viral.",

  "It prefers trainers who enjoy peaceful afternoons.",
  "It often appears during meteor showers.",
  "It enjoys accompanying picnics and tea parties.",
  "It helps lonely Pokemon find companions.",
  "It can be found near cozy cafes during winter.",
  "It likes sitting on books while people read.",
  "It became a local legend after protecting a village from a storm.",
  "It likes collecting flower petals as keepsakes.",
  "It only stays with trainers who are kind to wild Pokemon.",
  "It dreams of one day seeing the entire world beside its trainer."
]
};

